"""Fake Reviews Dataset (Salminen et al. 2022, "Creating and detecting fake reviews of online products"):
20k original Amazon reviews (OR) and 20k reviews generated by a fine-tuned GPT-2 (CG) across 10 product
categories. HF copy theArijitDas/Fake-Reviews-Dataset (label 1 = computer-generated), minus the 94
extra AI-written rows that copy added (they sit in categories outside the original 10).

Template "fake_reviews.generated": Noul "Was `review` written by a computer program rather than a real
customer?" Truth = label. Balanced 50/50, stratified by category, seeded hash order.
"""

from __future__ import annotations

import re
from collections import defaultdict
from pathlib import Path
from typing import Iterator

import httpx
import polars as pl

from askjev.model import Question
from askjev.sampling import env_int, hash_order

NAME = "fake_reviews"
URL = "https://huggingface.co/api/datasets/theArijitDas/Fake-Reviews-Dataset/parquet/default/train/0.parquet"
TARGET = env_int("TARGET_FAKE_REVIEWS", 2000)
LICENSE = "CC-BY-4.0 (Salminen et al. 2022; HF copy tagged Apache-2.0)"
TEXT = "Was `review` written by a computer program rather than a real customer?"
CRITERIA = {
    "true": "The review was generated by a text-generation program",
    "false": "The review was written by a real customer",
}
SEXUAL = re.compile(
    r"\b(sex|sexual\w*|sexy|porn\w*|nude\w*|naked|erotic\w*|horny|xxx|slut\w*|orgasm\w*|masturbat\w*|"
    r"steamy|bdsm|kink\w*|rape\w*|suicid\w*)\b",
    re.I,
)
CATEGORIES = {
    "Home_and_Kitchen", "Sports_and_Outdoors", "Electronics", "Movies_and_TV", "Tools_and_Home_Improvement",
    "Pet_Supplies", "Kindle_Store", "Books", "Toys_and_Games", "Clothing_Shoes_and_Jewelry",
}


def fetch(raw_dir: Path) -> None:
    out = raw_dir / "train.parquet"
    if out.exists():
        return
    r = httpx.get(URL, follow_redirects=True, timeout=120)
    r.raise_for_status()
    out.write_bytes(r.content)


def normalize(raw_dir: Path) -> Iterator[Question]:
    df = pl.read_parquet(raw_dir / "train.parquet").with_row_index("row")
    pools: dict[tuple[bool, str], list[tuple[int, str, float]]] = defaultdict(list)
    seen: set[str] = set()
    for row, cat, rating, text, label in df.select("row", "category", "rating", "text", "label").iter_rows():
        review = " ".join((text or "").split())
        key = review.lower()
        if cat not in CATEGORIES or len(review) < 20 or key in seen:
            continue
        seen.add(key)
        pools[(label == 1, cat)].append((row, review, rating))
    assert {c for _, c in pools} == CATEGORIES, {c for _, c in pools} ^ CATEGORIES

    picked = []
    cats = sorted(CATEGORIES)
    for label in (True, False):
        k = TARGET // 2 if label else TARGET - TARGET // 2
        orders = {c: hash_order(pools[(label, c)], lambda x: x[0], f"fake.{label}.{c}") for c in cats}
        # round-robin over categories so each gets ~k/10
        i = 0
        while k > 0:
            for c in cats:
                if k and i < len(orders[c]):
                    picked.append((label, c, orders[c][i]))
                    k -= 1
            i += 1
    picked.sort(key=lambda x: x[2][0])

    for label, cat, (row, review, rating) in picked:
        yield Question(
            text=TEXT,
            primitive="noul",
            hemisphere="machine",
            origin="dataset",
            source=NAME,
            options=CRITERIA,
            state={"review": review[:1500]},
            shape="detect",
            node_hint="machine.commerce.review_abuse",
            template_id="fake_reviews.generated",
            source_item_id=f"train:{row}",
            license=LICENSE,
            truth=label,
            meta={"category": cat, "rating": rating, "label_raw": "CG" if label else "OR",
                  **({"flags": ["sensitive"]} if SEXUAL.search(review) else {})},
        )
