"""Human or AI? Porter & Machery's poetry discrimination study (2024).

Human data: Porter & Machery 2024, "AI-generated poetry is indistinguishable from human-written poetry and is rated
more favorably", Scientific Reports 14:26133; data and survey files at https://osf.io/by4cg (no license stated; used
for non-commercial research). Study 1 showed 1,634 US adults poems by ten poets, five real and five written by
ChatGPT 3.5 "in the style of" each poet, and asked "Do you think this poem was written by a human, or generated by
an AI program?". Here: the poems of the seven poets whose real poems are in the public domain (Chaucer, Shakespeare,
Samuel Butler, Byron, Whitman, Dickinson, and T.S. Eliot's poems from 1917 and earlier); Ginsberg, Plath and Dorothea
Lasky are left out because their poems are under copyright. Each poem carries the study's split of answers.
"""

from __future__ import annotations

import csv
import re
import urllib.request
import zipfile
from collections import Counter, defaultdict
from pathlib import Path
from typing import Iterator

from askjev.model import HumanDist, Question

NAME = "ai_poetry"
NODE = "world.arts.books.poetry.human_or_ai"
LICENSE = "OSF by4cg (Porter & Machery 2024), no license stated; non-commercial research use. Poems: public domain or AI-generated"
FILES = {"study1.csv": "https://osf.io/download/7mvtj/", "study_text.docx": "https://osf.io/download/dkwqc/"}
POETS = {"Chaucer": "Chaucer", "Shakespeare": "Shakespeare", "Samuel Butler": "Butler", "Lord Byron": "Byron",
         "Walt Whitman": "Whitman", "Emily Dickinson": "Dickinson", "T.S. Eliot": "Eliot"}
OPTIONS = {"human": "Written by a human", "ai": "Generated by an AI program"}
KEY = {"human": "human", "AI": "ai"}


def fetch(raw_dir: Path) -> None:
    for f, u in FILES.items():
        if not (raw_dir / f).exists():
            urllib.request.urlretrieve(u, raw_dir / f)


def _poems(raw_dir: Path) -> dict[tuple[str, int], str]:
    x = zipfile.ZipFile(raw_dir / "study_text.docx").read("word/document.xml").decode()
    text = "\n".join(re.sub(r"<[^>]+>", "", p) for p in re.findall(r"<w:p[ >].*?</w:p>", x))
    out = {}
    for name, body in re.findall(r"Start of Block: (.+?)\n(.*?)End of Block", text, re.S):
        m = re.match(r"(\w[\w ]*?) (\d+)$", name.strip())
        if m and "the questions about it below:" in body:
            poem = body.split("the questions about it below:", 1)[1].split("Do you think this poem")[0]
            out[(m.group(1), int(m.group(2)))] = re.sub(r"[ \t]+", " ", poem).strip()
    return out


def normalize(raw_dir: Path) -> Iterator[Question]:
    poems = _poems(raw_dir)
    votes: dict[tuple[str, int], Counter] = defaultdict(Counter)
    author = {}
    for r in csv.DictReader(open(raw_dir / "study1.csv")):
        if r["Poet"] in POETS:
            k = (POETS[r["Poet"]], int(r["poem_ID"]))
            votes[k][KEY[r["Discrimination Response"]]] += 1
            author[k] = KEY[r["Authorship"]]
    for k in sorted(votes):
        c = votes[k]
        n = sum(c.values())
        yield Question(
            text=f"Was this poem written by a human, or generated by an AI program?\n\n{poems[k]}", primitive="choice",
            hemisphere="world", kind="perception", origin="dataset", source=NAME, options=OPTIONS, node_hint=NODE,
            license=LICENSE, source_item_id=f"{k[0]} {k[1]}", truth=author[k],
            human=[HumanDist(population="US adults (Porter & Machery 2024, Study 1, Prolific)",
                             distribution={o: c[o] / n for o in OPTIONS}, n=n,
                             source="OSF by4cg 'Study 1 Discrimination Data.csv', Discrimination Response per poem")],
            meta={"experiment": "ai_poetry", "poet": k[0], "poem_id": k[1], "author": author[k]})
