N_="self.personality.motivation_ambition"
C=[
("A leaderboard is posted at work showing everyone's monthly results. What do you usually do?",{"ignore_it":"ignore it","glance_once":"glance at it once","check_often":"check it often","push_to_top":"push hard to reach the top","other":None}),
("You have a free evening and an online course you signed up for weeks ago. What usually happens?",{"do_a_lesson":"you do a lesson","do_part":"you start and stop partway","plan_to_start_tomorrow":"you plan to start tomorrow","forget_it":"you forget about it","other":None}),
("When your boss offers a stretch project with no extra pay, what do you usually do?",{"take_it_eagerly":"take it eagerly for the challenge","take_it_for_career":"take it because it looks good","ask_for_pay":"ask for something in return","decline":"decline politely","other":None}),
("When you set a personal record, like your fastest run, what do you usually do next?",{"rest_and_enjoy":"rest and enjoy it","share_it":"share it with friends","set_a_new_target":"set a harder target right away","wonder_if_it_was_luck":"wonder if it was a fluke","other":None}),
("Which reason most often makes you finish a book you are not enjoying?",{"i_never_do":"you never do, you just stop","hate_quitting":"you hate leaving things unfinished","want_to_discuss_it":"you want to discuss it with others","hope_it_improves":"you hope it gets better","other":None}),
("When you are learning something new and someone else picks it up faster, what do you usually do?",{"learn_from_them":"ask them for tips","keep_my_pace":"keep going at your own pace","practice_extra":"practice extra to catch up","lose_interest":"lose interest","other":None}),
("When you have a big task, how do you usually break it up?",{"no_plan":"you just start and see","rough_steps":"you sketch a few rough steps","detailed_plan":"you write a detailed plan with milestones","wait_for_pressure":"you wait until pressure forces a plan","other":None}),
("When a hobby turns out to be harder than expected, what do you usually do?",{"push_through":"push through the hard part","take_lessons":"take lessons","switch_hobby":"switch to another hobby","keep_it_casual":"keep doing it casually without improving","other":None}),
("Which kind of recognition would you work hardest for?",{"public_award":"a public award","boss_praise":"private praise from your boss","peer_respect":"quiet respect from peers","own_pride":"your own sense of a job well done","money":"a cash bonus","other":None}),
("When you notice you have been scrolling on your phone instead of working, what do you usually do?",{"stop_right_away":"stop and get back to work","finish_one_more":"finish one more thing then stop","keep_scrolling":"keep scrolling a while longer","give_up_on_work":"give up on work for the day","other":None}),
("When a group project partner does less than their share, what do you usually do?",{"do_it_yourself":"do their part to make it great","push_them":"push them to do more","let_it_be_average":"accept an average result","report_it":"report it to the teacher or boss","other":None}),
("When you get a surprise day off, what do you usually do with it?",{"rest_fully":"rest fully","errands":"catch up on errands","personal_project":"work on a personal project","work_anyway":"do some work anyway","other":None}),
("When a friend suggests a race or challenge, how do you usually respond?",{"decline":"decline","join_for_fun":"join just for fun","join_to_win":"join and try hard to win","train_seriously":"train seriously to beat them","other":None}),
("When you fall short of a goal you set publicly, what do you usually do?",{"quietly_drop_it":"quietly drop it","explain_and_move_on":"explain what happened and move on","try_again_harder":"try again harder","set_a_new_goal":"pick a different goal","other":None}),
("Which kind of job would you choose if pay were the same?",{"easy_and_stable":"easy and stable","challenging_and_growing":"challenging with room to grow","prestigious":"prestigious","creative_and_free":"creative with lots of freedom","other":None}),
("When you are close to beating a hard level in a game, what do you usually do?",{"take_a_break":"take a break","try_a_few_more_times":"try a few more times","keep_going_until_done":"keep going until you beat it","look_up_a_guide":"look up a guide","other":None}),
("When someone praises you for effort instead of results, how do you usually feel?",{"pleased":"pleased","neutral":"neutral","a_bit_let_down":"a bit let down","push_for_results":"pushed to get real results next time","other":None}),
("When you set a goal, how do you usually track it?",{"do_not_track":"you do not track it","keep_in_head":"you keep it in your head","write_it_down":"you write it down and check it","use_an_app":"you use an app with reminders","other":None}),
("When someone gets a prize you wanted, what is your first thought?",{"good_for_them":"good for them","next_time":"next time it will be you","what_did_they_do":"what did they do that you did not","it_was_unfair":"it was unfair","other":None}),
("When you are tired but have unfinished work, what do you usually do?",{"stop_and_rest":"stop and rest","finish_the_essentials":"finish only the essentials","push_through":"push through to the end","stop_and_feel_guilty":"stop but feel guilty","other":None}),
("Why do you usually learn a new skill?",{"curiosity":"out of curiosity","for_a_job":"because work needs it","to_impress":"to impress others","to_be_the_best":"to become better than others","other":None}),
("How do you usually feel on the first day of a new job or class?",{"excited_to_prove_myself":"excited to prove yourself","calm_and_curious":"calm and curious","nervous_but_eager":"nervous but eager","hoping_to_get_by":"hoping just to get by","other":None}),
("When a task you care about gets harder than you thought, what usually drives you on?",{"stubbornness":"stubbornness","promise_to_others":"a promise you made to others","love_of_the_work":"love of the work itself","fear_of_failing":"fear of failing","nothing_i_stop":"nothing, you usually stop","other":None}),
("When you look back on a finished project, what do you usually focus on?",{"what_went_well":"what went well","what_to_improve":"what you could improve","what_others_think":"what others thought of it","what_is_next":"what you will do next","other":None}),
("What most often gets you to start a chore you have been avoiding?",{"guests_coming":"someone is coming over","a_deadline":"a deadline","a_reward_after":"a reward you promise yourself","sudden_energy":"a burst of energy","it_gets_done_eventually":"nothing, it waits a long time","other":None}),
("When you are in a race you know you cannot win, what do you usually do?",{"give_full_effort":"give full effort anyway","beat_my_own_time":"try to beat your own time","ease_off":"ease off","drop_out":"drop out","other":None}),
("When someone offers you a job with more status but less meaning, what do you usually lean toward?",{"status":"the job with more status","meaning":"the job with more meaning","ask_for_time":"ask for time to decide","depends_on_pay":"the one that pays more","other":None}),
("When a coworker is praised for hard work, what do you usually do?",{"congratulate":"congratulate them","study_their_approach":"study how they work","work_harder":"work harder yourself","nothing":"nothing in particular","other":None}),
("How do you usually approach a new sport with friends?",{"just_for_fun":"just for fun","learn_the_basics":"learn the basics properly","practice_to_beat_them":"practice to beat them","avoid_looking_bad":"try mainly to avoid looking bad","other":None}),
("When you finish a task early, what do you usually do?",{"relax":"relax","check_it_again":"check it again","start_the_next_task":"start the next task","offer_help":"offer to help others","other":None}),
("Which do you usually enjoy most about a long project?",{"the_start":"the exciting start","the_middle_grind":"the steady middle","the_finish":"the finish","the_reward_after":"the reward after","other":None}),
("When you are asked where you see yourself in the future, how do you usually answer?",{"clear_plan":"with a clear plan","rough_idea":"with a rough idea","big_dream":"with a big dream","no_idea":"you have no idea","other":None}),
]
S=[
("When a work task is due in two weeks, when do you usually start?",["I start the day it is assigned","I start within a few days","I start around the halfway point","I start a few days before it is due","I start the night before"]),
("When you lose a close game, what do you usually do afterward?",["I forget about it","I shrug it off","I think about what went wrong","I practice to get better","I insist on a rematch right away"]),
("When a hard puzzle stumps you, how long do you usually keep at it?",["I give up at once","I try for a few minutes","I try until I get bored","I keep at it for hours","I cannot rest until I solve it"]),
("When you are given a goal at work, how much higher do you aim?",["I aim a bit below it to be safe","I aim for exactly the goal","I aim a little above it","I aim well above it","I aim to set a new record"]),
("When nobody will notice extra effort on a task, how much do you put in?",["I do the bare minimum","I do what is required","I add small improvements","I do it as if my boss were watching","I polish it far beyond what anyone expects"]),
("When a friend is better than you at your favorite hobby, what do you usually do?",["I stop doing the hobby","I avoid doing it with them","I enjoy it without comparing","I ask them to teach me","I train to catch up and pass them"]),
("How do you usually react when you receive a rejection letter?",["I give up on that path","I feel down for a long time","I feel down for a day then move on","I apply somewhere else right away","I ask for feedback and reapply"]),
("How often do you set goals for yourself without anyone asking?",["I never do","I rarely do","I do now and then","I often do","I always have a few going"]),
("When a boring but important form needs filling out, how long do you usually wait?",["I do it right away","I do it the same day","I do it within the week","I wait until someone reminds me","I wait until it is overdue"]),
("How do you usually feel about getting a participation award?",["I feel proud of it","I feel fine about it","I feel indifferent","I feel a bit embarrassed","I feel it pushes me to win next time"]),
("When a teammate slacks off during a game, how do you usually respond?",["I slack off too","I say nothing","I encourage them","I cover for them by playing harder","I call them out to win"]),
("How much do you care about being the best person in your workplace at something?",["I do not care at all","I care a little","I care somewhat","I care a lot","It is one of my main goals"]),
("When learning a language, how much practice do you usually do beyond the lessons?",["I skip the lessons too","I do only the lessons","I do a little extra practice","I practice every day on my own","I seek out native speakers to practice with"]),
("When you have a chance to lead a project, how do you usually react?",["I turn it down","I accept only if asked twice","I accept calmly","I accept eagerly","I go after it before anyone else can"]),
("How often do you start the day with a written plan?",["I never do","I rarely do","I sometimes do","I usually do","I always do"]),
("When your progress on a goal stalls, how do you usually respond?",["I quit","I lose interest slowly","I keep going the same way","I try a new approach","I double my effort and try new approaches"]),
("When you win a small contest, like a raffle quiz, how much do you celebrate?",["I do not care","I smile to myself","I tell a friend","I tell everyone","I plan to win the next one too"]),
("When you have a side project, how often do you work on it?",["I have no side projects","Only when I remember","Now and then","Most weeks","Almost every day"]),
("When you see a skill you want in someone else, how soon do you start working on it?",["I never do","I think about it for months","I start eventually","I start within days","I start the same day"]),
("How much do you enjoy friendly competition at work or school?",["I avoid it","I tolerate it","I enjoy it a little","I enjoy it a lot","I seek it out and thrive on it"]),
]
Nq=[
"Do you keep going on a hard task mainly because you hate to quit?",
"Do you enjoy work more when there is a scoreboard?",
"Do you pick harder routes or levels just for the challenge?",
"Do you work on your own goals during weekends?",
"Do you feel proud of work even when no one else sees it?",
"Do you often wait for inspiration before starting a task?",
"Do you push yourself to finish a workout even when you feel like stopping?",
"Do you read or study things for work in your free time?",
"Do you feel a strong need to beat your own past results?",
"Do you often lose interest in goals after the first week?",
"Do you ask for more responsibility at work or school?",
"Do you work harder when a reward is promised?",
"Do you keep trying after being told you are not good enough?",
]
