N_="self.personality.humor_style"
C=[
("Your team's big presentation crashes because the projector dies. What do you usually say?",{"stay_serious":"nothing funny, just fix it","light_joke":"a light joke to ease the room","joke_about_yourself":"a joke about your own tech skills","joke_about_the_tech_team":"a jab at whoever set it up","other":None}),
("A friend sends you a photo of a very ugly sweater they bought. How do you usually reply?",{"sincere_compliment":"a sincere compliment","playful_tease":"a playful tease","over_the_top_praise":"mock over the top praise","brutal_roast":"a brutal roast","other":None}),
("When you get lost while driving with friends, how do you usually handle it?",{"stay_quiet":"focus quietly on finding the way","joke_about_it":"joke that it is a scenic detour","blame_the_map":"joke about the useless map","tease_the_navigator":"tease whoever was navigating","other":None}),
("Which kind of humor do you most enjoy in a movie?",{"slapstick":"physical slapstick","witty_dialogue":"witty dialogue","absurd_surreal":"absurd, surreal scenes","dark_comedy":"dark comedy","awkward_moments":"painfully awkward moments","other":None}),
("When a teacher or boss makes a mistake in front of the room, what do you usually do?",{"nothing":"say nothing","smile_along":"smile along with them","quick_quip":"make a quick friendly quip","whisper_jokes":"whisper jokes about it to a neighbor","other":None}),
("Which do you most often send in a group chat?",{"funny_gif":"a funny animated image","witty_comment":"a witty comment","inside_joke":"an inside joke","gentle_teasing":"gentle teasing of a friend","rarely_joke":"you rarely joke in chats","other":None}),
("When you spill coffee on yourself before an important meeting, what do you usually do?",{"hide_it":"try to hide it","laugh_it_off":"laugh it off and mention it","make_it_a_bit":"turn it into a running joke all day","get_annoyed":"stay annoyed","other":None}),
("Which kind of friend makes you laugh the most?",{"the_storyteller":"the one who tells great stories","the_deadpan":"the one with a dry, deadpan delivery","the_goofball":"the one who acts silly","the_roaster":"the one who roasts everyone","other":None}),
("When someone tells a joke you have heard before, what do you usually do?",{"laugh_anyway":"laugh anyway","say_you_know_it":"say you know it","finish_it_for_them":"deliver the punchline first","add_a_twist":"add a twist to it","other":None}),
("How do you usually sign off a funny email or message?",{"normal_signoff":"a normal sign-off","silly_emoji":"a silly emoji","pun":"a pun related to the topic","mock_formal":"a mock formal sign-off","other":None}),
("When you are the new person in a group, which humor do you use first?",{"none_yet":"none until you know them","self_deprecating":"jokes about yourself","observational":"jokes about the situation","playful_teasing":"playful teasing of others","other":None}),
("When someone mispronounces a word in conversation, what do you usually do?",{"ignore_it":"ignore it","gently_correct":"gently correct them","repeat_it_funny":"repeat it later as a joke","tease_right_away":"tease them right away","other":None}),
("Which topic do you most often joke about?",{"yourself":"yourself","daily_life":"everyday life","friends":"your friends","work_or_school":"work or school","current_trends":"trends online","other":None}),
("When a formal event gets stiff and quiet, what do you usually do?",{"stay_proper":"stay proper and wait","whisper_jokes":"whisper jokes to the person next to you","make_the_room_laugh":"try to make the whole table laugh","make_faces":"make faces at a friend","other":None}),
("Which birthday prank would you most enjoy pulling on a friend?",{"no_pranks":"no pranks, just a nice gift","silly_decorations":"covering their desk in silly decorations","fake_gift":"a fake gift box inside a box inside a box","embarrassing_photo":"a cake printed with an embarrassing photo","other":None}),
("When you lose a friendly bet, how do you usually take it?",{"pay_quietly":"pay up quietly","joke_about_losing":"joke about your bad luck","demand_a_rematch_jokingly":"demand a rematch in mock outrage","other":None}),
("When a child tells you a joke that makes no sense, what do you usually do?",{"laugh_warmly":"laugh warmly","explain_how_jokes_work":"explain how the joke should go","tell_one_back":"tell one back","play_along_absurdly":"play along with even sillier nonsense","other":None}),
("When a coworker teases you about your messy desk, how do you usually respond?",{"laugh_along":"laugh along","joke_back":"joke back about their desk","explain_yourself":"explain why it is messy","feel_stung":"feel stung and stay quiet","other":None}),
("Which kind of video are you most likely to rewatch just to laugh?",{"animal_fails":"animals doing silly things","people_fails":"people failing at stunts","sketch_comedy":"short comedy sketches","clever_parodies":"clever parodies","other":None}),
("When a stressful week finally ends, how does your humor usually show?",{"no_jokes":"you are too tired to joke","silly_mood":"you get silly and goofy","dark_jokes":"you make dark jokes about the week","sarcastic_rundown":"you give a sarcastic rundown of it","other":None}),
("How do you usually react when someone laughs at your honest mistake?",{"laugh_too":"laugh too","make_it_bigger":"exaggerate it for more laughs","feel_embarrassed":"feel embarrassed","snap_back":"snap back at them","other":None}),
("Which kind of wordplay do you enjoy most?",{"puns":"puns","rhymes":"silly rhymes","double_meanings":"clever double meanings","none":"none, wordplay bores you","other":None}),
("When you tell a funny story, which style do you usually use?",{"short_and_dry":"short and dry","dramatic_voices":"dramatic voices and gestures","long_buildup":"a long buildup to the punchline","facts_only":"just the facts and let it speak","other":None}),
("When your friend group starts roasting each other, what do you usually do?",{"watch_and_laugh":"watch and laugh","join_gently":"join with gentle jabs","go_all_in":"go all in with the sharpest lines","step_out":"step out of it","other":None}),
("When something breaks at home, like a door handle coming off, what is your usual reaction?",{"just_fix_it":"just fix it","laugh_at_it":"laugh at how absurd it is","joke_to_housemates":"make a joke to whoever is home","curse_at_it":"curse at it","other":None}),
("Which kind of card or note do you usually leave for a coworker's farewell?",{"heartfelt":"a heartfelt message","inside_joke":"an inside joke","funny_drawing":"a funny drawing","mock_insult":"a playful mock insult","other":None}),
("When a friend is taking themselves too seriously, what do you usually do?",{"let_them_be":"let them be","gentle_joke":"make a gentle joke to lighten them up","exaggerate_their_mood":"exaggerate their mood as a bit","point_it_out":"point it out bluntly","other":None}),
("Which of these do you find funniest in a comedy show?",{"timing":"perfect timing","characters":"odd characters","callbacks":"jokes that return later","shock":"shocking lines","other":None}),
("When you play board games with friends, how do you usually use humor?",{"focus_on_game":"focus on the game","trash_talk":"playful trash talk","laugh_at_your_mistakes":"laugh at your own bad moves","narrate_the_game":"narrate the game like a sportscaster","other":None}),
("When a waiter jokes with you at a restaurant, how do you usually respond?",{"polite_smile":"a polite smile","laugh_heartily":"laugh heartily","joke_back":"joke back","feel_awkward":"feel a bit awkward","other":None}),
("When a friend's cooking goes badly wrong, what do you usually say?",{"kind_words":"say something kind","gentle_joke":"make a gentle joke","dramatic_review":"give a mock dramatic food review","order_pizza_joke":"joke about ordering pizza","other":None}),
("Which kind of humor do you use most with family?",{"shared_stories":"retelling old family stories","teasing_siblings":"teasing siblings or cousins","silly_voices":"silly voices","dry_comments":"dry comments","little_humor":"you do not joke much with family","other":None}),
]
S=[
("When someone at a gathering tells a joke that falls flat, how do you usually react?",["I stay silent","I give a polite smile","I laugh to help them out","I make a joke about the flop to rescue it","I tease them about it for the rest of the night"]),
("When you have to give bad news to a friend, how much humor do you use?",["I use none at all","I add a small smile at the end","I soften it with one light joke","I wrap most of it in jokes","I turn the whole thing into a comedy routine"]),
("When a coworker shows up in an odd outfit, what do you usually do?",["I say nothing","I compliment it kindly","I make a gentle joke","I tease them in front of others","I keep joking about it all day"]),
("How do you usually react when you trip in public?",["I hurry away feeling embarrassed","I pretend nothing happened","I smile to myself","I laugh out loud at myself","I do a mock bow for anyone watching"]),
("How often do you use funny voices or impressions when telling a story?",["I never do","I rarely do","I sometimes do","I often do","I do it in nearly every story"]),
("When a meeting runs long, how much joking do you do in side messages?",["I send no side messages","I send one quick comment","I send a few jokes to a friend","I keep a joke thread going","I run a full comedy commentary"]),
("How do you usually handle a friend's bad pun?",["I ignore it","I groan","I laugh","I reply with a worse pun","I start a pun battle that lasts ages"]),
("When you see a funny typo in a public sign, what do you usually do?",["I do not notice or care","I smile and walk on","I point it out to whoever is with me","I take a photo to share","I post it with a clever caption"]),
("When you are in pain, like after stubbing a toe, how much do you joke about it?",["I never joke about it","I joke once it stops hurting","I make a small joke right away","I make a big dramatic show of it","I turn it into a story for days"]),
("How dark do your jokes get with close friends?",["I keep them clean","I go a little edgy","I joke about grim topics sometimes","I often joke about grim topics","I push dark humor as far as I can"]),
("When you tease someone and they look hurt, what do you usually do?",["I never tease in the first place","I apologize right away","I say I was only kidding","I carry on a little","I tease them more for being sensitive"]),
("How often do you laugh at jokes you do not really find funny?",["I never fake a laugh","I rarely do","I do it to be polite sometimes","I often do","I do it almost every time"]),
("When you tell a joke, how much do you wait for others to laugh first?",["I do not tell jokes","I only tell them if I am sure they will land","I tell them and wait nervously","I tell them freely","I laugh at my own jokes whether or not others do"]),
("When a friend repeats your joke and gets the laugh, how do you usually react?",["I am glad people laughed","I laugh along","I smile but feel a small pang","I point out it was my joke","I stay annoyed about it"]),
("How often do you use sarcasm with strangers, like shop staff?",["I never do","I rarely do","I sometimes do","I often do","I do it almost every time"]),
("When your day goes badly, how much do you joke about it to others?",["I do not mention it","I mention it plainly","I add a small joke","I make it into a funny story","I perform it as a full comedy bit"]),
("When someone roasts you in front of a crowd, how do you usually respond?",["I feel crushed and leave","I stay quiet and blush","I laugh along","I roast them back lightly","I fire back harder than they did"]),
("How do you usually react to a surprise water balloon or silly prank from a friend?",["I get angry","I feel annoyed but hide it","I laugh it off","I laugh and plan a gentle revenge","I launch a full prank war"]),
("How much of your humor depends on inside jokes with close friends?",["None of it","A little","About half","Most of it","Almost all of it"]),
("When a serious conversation turns heavy, how quickly do you reach for a joke?",["I never do","Only after it is resolved","When there is a natural pause","Fairly quickly","Almost right away"]),
]
Nq=[
"Do you often joke about how bad you are at something?",
"Do you enjoy humor that makes fun of how people talk or act?",
"Do you use a joke to change the subject when a conversation gets uncomfortable?",
"Do you enjoy long running gags that last for years among friends?",
"Do you find it funny when animals act like people?",
"Do you often make jokes that only you find funny?",
"Do you tease people you like more than people you do not?",
"Do you enjoy deadpan jokes delivered with a straight face?",
"Do you save funny moments on your phone to show people later?",
"Do you enjoy jokes that play on awkward social moments?",
"Do you make jokes about your own worries to feel better about them?",
"Do you like to write funny captions or comments online?",
"Do you enjoy making friends laugh so hard they cannot speak?",
]
