N_="self.personality.type.sn"
C=[
("When you visit a new city, what do you tend to remember afterward?",[("specific_sights","specific streets, meals, and sights"),("overall_feel","the overall mood and what it made you imagine")]),
("When you buy a new phone, what do you focus on?",[("specs","the actual specs and proven features"),("potential","what it could let you do in new ways")]),
("When you hear a friend's business idea, what do you ask about first?",[("practical_details","costs, logistics, and who the customers are"),("big_vision","where the idea could lead in the long run")]),
("When you garden, which approach appeals to you more?",[("proven_method","following proven planting advice"),("experiment","trying unusual layouts and plant combinations")]),
("When a teacher explains a formula, what helps you more?",[("worked_example","seeing it applied to a real example"),("underlying_idea","understanding the idea behind it")]),
("When you describe your job to someone, what do you talk about?",[("daily_tasks","the concrete tasks you do each day"),("purpose","the bigger purpose and where it is heading")]),
("When you read a product review, which part do you value?",[("hands_on_facts","hands-on facts about how it performs"),("overall_take","the reviewer's overall take and comparisons")]),
("Which kind of museum exhibit holds your attention longer?",[("real_objects","real objects with detailed labels"),("concept_exhibit","an exhibit built around a big idea")]),
("When you look at an old photo, what catches you first?",[("details_in_it","details like clothes, cars, and objects"),("story_behind","the story or feeling behind the moment")]),
("When your manager announces a reorganization, what is your first concern?",[("what_changes_tomorrow","what changes in your daily work"),("where_it_leads","what it signals about the future")]),
("When you choose a route for a walk, which do you prefer?",[("known_route","a route you know well"),("new_path","a new path just to see where it goes")]),
("When you learn a language, which approach suits you?",[("phrases_first","useful phrases for real situations"),("grammar_patterns","the patterns and logic of the grammar")]),
("When a friend describes a dream they had, what do you do?",[("listen_to_events","listen to what happened in it"),("interpret_it","wonder what it might mean")]),
("When writing a birthday card, which comes easier?",[("specific_memory","recalling a specific shared memory"),("wishes_for_future","writing hopes for their future")]),
("When you evaluate a new coworker, what do you rely on?",[("track_record","what they have actually done so far"),("sense_of_potential","your sense of what they could become")]),
("When you watch a science documentary, what grabs you more?",[("facts_and_footage","the facts and the footage"),("big_questions","the big questions it raises")]),
("When fixing something broken at home, what do you do first?",[("inspect_parts","inspect each part closely"),("guess_the_cause","form a hunch about the overall cause")]),
("When planning a meal for guests, which is more like you?",[("tried_dishes","cook dishes you have made before"),("new_concept","invent a themed menu you have never tried")]),
("When a friend describes their new apartment, what do you want to know?",[("layout_and_size","the layout, size, and rent"),("feel_of_it","how it feels and what they will do with it")]),
("When you read a poem, which do you notice first?",[("words_and_images","the actual words and images"),("hidden_meaning","the hidden meaning beneath them")]),
("When you brainstorm a gift idea, which do you lean toward?",[("something_needed","something they clearly need"),("something_symbolic","something symbolic that says more")]),
("When a job listing is vague, what bothers you more?",[("missing_specifics","missing specifics about duties and pay"),("missing_mission","a missing sense of mission")]),
("When someone tells you about a new theory in a field, what is your reaction?",[("show_evidence","ask to see the evidence"),("explore_implications","start exploring what it would imply")]),
("When you set up a new room, which do you start with?",[("measure_first","measuring the space and furniture"),("picture_mood","picturing the mood you want")]),
("When you prepare for a trip abroad, what do you read about?",[("practical_info","transport, prices, and opening hours"),("culture_and_history","the culture, history, and ideas of the place")]),
("When comparing two schools or courses, what matters more?",[("concrete_outcomes","the concrete facts like cost and results"),("atmosphere_and_vision","the atmosphere and what they aim to be")]),
("When you listen to a lecture, which kind of speaker keeps you engaged?",[("examples_speaker","one full of concrete examples"),("ideas_speaker","one full of sweeping ideas")]),
("When you describe a meal you enjoyed, what do you mention?",[("ingredients","the ingredients and how it was cooked"),("impression","the overall experience it created")]),
("When you plan your savings, what do you think about most?",[("current_numbers","the current balance and bills"),("future_scenarios","scenarios of what the money could make possible")]),
("When you watch a sports game, what do you focus on?",[("plays_happening","the plays as they happen"),("strategy_arc","the larger strategy and how the season might unfold")]),
("When someone hands you a new gadget with no manual, what do you do?",[("press_buttons","press each button to see what it does"),("guess_design","guess the design logic behind it")]),
("When you talk with a child about stars, what do you tell them?",[("names_and_facts","names and facts about them"),("wonder_questions","wonder about what might be out there")]),
("When your team starts a new project, which kind of kickoff helps you?",[("task_list","a clear task list and timeline"),("vision_talk","a talk about the vision and why it matters")]),
("When you are asked for your opinion on a movie, what do you usually discuss?",[("plot_and_acting","the plot and the acting"),("themes","the themes and what it was really about")]),
("When you learn about a historical event, what interests you more?",[("what_happened","exactly what happened and when"),("what_it_meant","what it meant and how it shaped later times")]),
("When you are making a decision about a used car, which do you trust?",[("inspection","a careful inspection and service records"),("overall_hunch","your overall hunch about the car")]),
("When you see a strange sculpture in a park, what do you do?",[("read_plaque","read the plaque for facts about it"),("imagine_meaning","imagine what the artist meant")]),
("When someone asks what you want to do in the future, how do you answer?",[("next_steps","describe your next practical steps"),("dream_picture","describe a bigger picture of your dreams")]),
("When a friend is house hunting, what advice do you give?",[("check_the_basics","check plumbing, commute, and costs"),("imagine_life_there","imagine the life you would have there")]),
("When you keep a journal, what fills it?",[("events_of_day","records of what happened"),("reflections_ideas","reflections, ideas, and musings")]),
("When a plan at work seems odd, what do you question?",[("will_it_work","whether it will work in practice"),("what_it_assumes","what deeper assumption it rests on")]),
("When you join a new hobby group, what do you want first?",[("rules_and_basics","the rules and the basics"),("why_people_love_it","why people find it meaningful")]),
("When a friend is telling a long story, which is more like you?",[("follow_details","following every detail"),("skip_to_point","wanting to skip to the point and the meaning")]),
]
S=[
("When you give a friend a tour of your hometown, what do you point out?",["exact street names and shop details","practical spots like the best bakery","a mix of places and their stories","the feel of each area and its history","what the town could become someday"]),
("When you learn a new board game, how do you want it explained?",["read me every rule in order","walk me through a sample turn","show me the basics then let me play","tell me the goal and let me figure it out","just tell me the idea behind it"]),
("When you write a report at work, what does it mostly contain?",["hard data and exact figures","facts with a short summary","facts and some interpretation","mostly interpretation and trends","mostly ideas about what could come next"]),
("How do you usually approach cooking a dish for the first time?",["I follow the recipe exactly","I follow it closely with small tweaks","I use it as a rough guide","I glance at it and improvise","I invent my own version from the idea alone"]),
("When a coworker pitches a bold idea, how do you respond?",["I list every practical problem","I ask for concrete evidence first","I weigh it against what I know","I get curious about where it could go","I start adding bigger ideas to it"]),
("When you plan a garden or balcony, how do you choose plants?",["only ones I know grow well here","mostly reliable ones with a few new ones","a balance of known and new","mostly unusual ones to experiment","whatever sparks an idea for a theme"]),
("How do you read a news article?",["I focus on the facts reported","I note the key facts and quotes","I read facts and think about causes","I think about what it means for the future","I imagine the wider story it hints at"]),
("When you describe a person to someone who has not met them, what do you say?",["their looks and what they do","their habits and routines","a mix of details and impressions","the vibe they give off","what I sense they could become"]),
("When you notice a pattern in your own habits, what do you do?",["I rarely notice patterns like that","I notice but move on","I think about it briefly","I think about what it says about me","I build a whole theory from it"]),
("How do you usually prepare for a job interview?",["I rehearse exact answers about my experience","I list concrete examples to mention","I prepare examples and a general story","I think mainly about the big story I want to tell","I imagine where the job could take me"]),
("When you shop for a gift, how do you decide?",["I buy what they asked for","I pick something practical they will use","I mix usefulness with a personal touch","I look for something meaningful to them","I pick something that represents an idea about them"]),
("How much do you enjoy conversations about how life might be in a hundred years?",["I find them pointless","I tolerate them briefly","I enjoy them now and then","I really enjoy them","I could talk about it all night"]),
("When you assemble a model or kit, how closely do you follow the steps?",["I follow each step exactly","I follow the steps with a quick look ahead","I skim and then follow","I use the picture and wing it","I build my own version"]),
("When your friend describes a problem, what do you focus on?",["exactly what happened","the key facts","the facts and what they might mean","the pattern behind it","the bigger lesson it points to"]),
("When you look at a job posting, what do you read closely?",["the duties and requirements line by line","the pay and practical details","both details and the company pitch","the company vision","what the role could lead to someday"]),
("When you explore a bookstore, where do you drift?",["practical how-to books","history and true stories","a mix of sections","fiction and big-idea books","books about speculative futures or theories"]),
("How do you recall your last holiday?",["a precise list of places and meals","clear scenes and details","a few scenes and a general feeling","mostly the feeling of it","mostly what it made me think about"]),
("When you set goals for the new year, what do they look like?",["exact tasks and checklists","concrete targets","a mix of targets and themes","broad themes","a big vision of who I want to be"]),
("When a friend explains a new app idea, what do you picture?",["the exact screens and buttons","how it would work day to day","how it works and who would use it","how it could change habits","a whole new world built around it"]),
("How do you feel about work that requires close attention to small details all day?",["I thrive on it","I enjoy it most days","it is fine in moderation","I find it tiring","I find it draining and dull"]),
("When a conversation turns to what-if scenarios, what do you do?",["I steer it back to real things","I join briefly then move on","I play along a while","I dive in happily","I keep inventing new scenarios"]),
("When you read a manual for a new appliance, what do you do?",["I read it cover to cover","I read the relevant sections","I skim it quickly","I glance at the diagrams only","I never open it"]),
("When you make a presentation, what do you lead with?",["specific data points","a concrete example","a mix of example and idea","the main concept","a vision of what could be"]),
("When you see an abstract painting, what do you do?",["I look for what it literally shows","I notice colors and technique","I take in both technique and mood","I think about what it means","I spin a whole story from it"]),
("When deciding where to live, what matters most?",["the exact commute and costs","practical facts about the area","facts plus the general feel","the feel of the place","what life there could become"]),
]
NN=[
"Do you usually notice when furniture in a familiar room has been moved?",
"Do you often find yourself thinking about how things could be done completely differently?",
"Do you prefer a teacher who gives step-by-step instructions?",
"Do you often read the last page of a story to guess the whole theme?",
"Do you usually remember exact words people said to you?",
"Do you tend to see links between unrelated topics during a conversation?",
"Do you prefer practical gifts over symbolic ones?",
"Do you often lose track of the present because you are imagining future plans?",
"Do you usually trust what you can see and measure over a gut sense?",
"Do you often come up with ideas that others call far-fetched?",
"Do you like having a clear example before trying something new?",
"Do you often wonder about the meaning behind everyday routines?",
"Do you usually stick to methods that have worked for you before?",
"Do you tend to read metaphors into things other people take literally?",
"Do you usually notice prices and exact numbers on menus and signs?",
"Do you often start projects because of the possibilities rather than the practical need?",
"Do you prefer conversations about real events over speculative ideas?",
]
