N_="self.personality.type.tf"
C=[
("When a friend shows you a painting they made and it is clumsy, what do you focus on?",[("technical_flaws","pointing out what could be improved"),("their_pride","their pride and effort in making it")]),
("When your landlord offers a small discount if you sign fast, how do you decide?",[("run_the_numbers","compare the numbers carefully"),("how_it_feels","go with how the place and landlord feel to you")]),
("When a volunteer group must choose which cause to fund, what should decide?",[("most_impact","which cause does the most measurable good"),("members_passion","which cause the members care about most")]),
("When a friend asks whether to take a higher-paying job away from family, what do you stress?",[("career_logic","the career and money logic"),("family_bonds","what it means for their relationships")]),
("When a waiter gets your order wrong, what shapes your reaction?",[("the_mistake","the mistake itself and fixing it"),("the_waiter","how the waiter is feeling")]),
("When your team votes on a plan, which argument sways you more?",[("data_argument","one backed by data"),("people_argument","one about how people will be affected")]),
("When you choose a charity to give to, what guides you?",[("efficiency","how efficiently it uses donations"),("personal_connection","a personal connection to its cause")]),
("When your partner in a class project writes a weak section, what do you do?",[("rewrite_it","rewrite it so the project is strong"),("coach_gently","coach them gently so they stay motivated")]),
("When deciding whether to lend money to a relative, what weighs more?",[("repayment_odds","whether they are likely to repay"),("their_need","how much they need it and your bond")]),
("When a movie's plot has holes but the story moves you, how do you rate it?",[("mark_it_down","mark it down for the plot holes"),("rate_it_high","rate it highly for how it made you feel")]),
("When your friend group can't agree on a restaurant, what do you suggest?",[("fair_rule","a fair rule like taking turns"),("most_wanted","going where it would make the most people happy")]),
("When a coach must cut a player from a team, what should decide?",[("skill_stats","skill and performance numbers"),("team_spirit","attitude and effect on team morale")]),
("When you are asked to write a reference for a friend, how do you write it?",[("accurate_record","an accurate, balanced record"),("warm_advocacy","a warm letter that champions them")]),
("When someone apologizes for a mistake that cost you time, what do you focus on?",[("preventing_repeat","how to stop it happening again"),("reassuring_them","reassuring them it is okay")]),
("When you plan a family trip, which concern leads?",[("cost_and_logistics","the cost and logistics"),("everyone_happy","making sure everyone is happy")]),
("When a new policy at school is efficient but unpopular, where do you stand?",[("support_efficiency","support it for its efficiency"),("side_with_people","side with the people who dislike it")]),
("When a friend asks if their new haircut looks good and it doesn't, what do you say?",[("honest_take","give your honest take"),("kind_take","find something kind to say")]),
("When a stranger's argument online is wrong but they seem hurt, what do you do?",[("correct_it","correct the argument anyway"),("leave_it","leave it to spare their feelings")]),
("When choosing a doctor, which matters more to you?",[("expertise","their record and expertise"),("bedside_manner","their warmth and bedside manner")]),
("When your group must pick a leader, what should decide?",[("most_competent","who is most competent"),("most_trusted","who people feel closest to")]),
("When you read a heartfelt letter with poor grammar, what stands out to you?",[("the_errors","the errors"),("the_feeling","the feeling in it")]),
("When a friend asks whether their poem is ready to submit, what guides your answer?",[("quality_standard","how it compares to the standard"),("their_hopes","how much it means to them")]),
("When your manager asks you to rank your teammates, what do you rank by?",[("output","their output and results"),("contribution_to_team","how they lift the people around them")]),
("When two friends ask you to choose one of their birthday parties on the same night, how do you choose?",[("logical_reason","whichever makes more sense by timing or distance"),("who_needs_you","whichever friend would be more hurt if you missed it")]),
("When a teammate proposes an idea based on a personal story, how do you weigh it?",[("wants_evidence","you want evidence beyond the story"),("story_counts","the story counts for a lot")]),
("When you plan a surprise for someone, which part do you focus on?",[("execution","getting the logistics exactly right"),("their_reaction","how they will feel")]),
("When your neighbor's tree drops leaves in your yard, how do you think about it?",[("whose_responsibility","whose responsibility it is"),("keeping_peace","keeping good relations")]),
("When a friend's pet dies and they ask why it happened, what do you give?",[("medical_explanation","a clear explanation of the likely cause"),("comfort","comfort and shared sadness")]),
("When you win a close game against a younger player, what do you do?",[("win_fairly","take the win since it was fair"),("ease_the_loss","soften it so they do not feel bad")]),
("When you decide between two apartments, what tips the scale?",[("spec_sheet","the spec sheet comparison"),("where_you_feel_at_home","where you feel more at home")]),
("When a manager must choose whom to promote, which approach do you favor?",[("merit_only","merit and results only"),("merit_and_circumstance","merit plus people's circumstances")]),
("When you help settle an argument between siblings, what do you look for?",[("who_is_right","who is actually right"),("what_calms_them","what will calm both of them")]),
("When an elderly relative tells a story with wrong facts, what do you do?",[("correct_facts","correct the facts"),("let_it_go","let it go and enjoy the story")]),
("When you give a speech at a friend's farewell, what fills it?",[("achievements","their achievements and facts"),("feelings","feelings and memories")]),
("When choosing between a cheaper supplier and a loyal old one, which do you pick?",[("cheaper","the cheaper supplier"),("loyal_one","the loyal old one")]),
("When someone makes a sincere but flawed proposal to your club, what is your first move?",[("critique_it","critique the flaws"),("thank_first","thank them warmly before anything else")]),
("When you vote in a contest among friends' baking, how do you vote?",[("best_cake","for the objectively best cake"),("who_tried_hardest","for whoever tried hardest or needs a lift")]),
("When a friend's plan makes no sense to you, what do you ask?",[("how_will_it_work","how it will work"),("what_it_means_to_them","what it means to them")]),
("When you evaluate an essay for a contest, which weighs more?",[("argument_quality","the quality of the argument"),("emotional_power","the emotional power")]),
("When a colleague cries in a meeting, what is your instinct?",[("keep_agenda","keep the meeting on track"),("pause_for_them","pause and check on them")]),
("When a close friend pitches you to join their venture, how do you decide?",[("evaluate_venture","evaluate the venture on its merits"),("support_friend","lean toward supporting your friend")]),
("When a game has an unfair rule that everyone enjoys, what do you want?",[("fix_rule","fix the rule"),("keep_fun","keep it for the fun")]),
("When you break up a tie in a group vote, how do you decide?",[("better_argument","by the better argument"),("keep_harmony","by what keeps the group happiest")]),
]
S=[
("When a friend asks you to review their resume, how do you give feedback?",["I list every flaw bluntly","I list flaws with brief explanations","I mix praise and criticism evenly","I lead with praise and soften the flaws","I mostly encourage and mention little criticism"]),
("When deciding who gets the best room on a group trip, what do you go by?",["a strict fair rule like drawing lots","who paid more","a mix of fairness and needs","who would enjoy it most","whoever seems to need a lift"]),
("When you break bad news to a coworker, how do you phrase it?",["I state the facts plainly","I state the facts with a short reason","I state the facts and show some sympathy","I focus on their feelings and then the facts","I soften it so much it barely sounds bad"]),
("When a friend's decision seems unwise, how do you respond?",["I explain exactly why it is wrong","I lay out the risks","I ask questions to help them think","I support them while voicing a worry","I back them fully because it matters to them"]),
("When your team member makes the same error again, how do you react?",["I point out the error firmly","I explain the error and the fix","I ask what is making it hard","I reassure them and offer help","I quietly fix it so they don't feel bad"]),
("When you choose between two candidates for a volunteer role, how much does personal warmth count?",["not at all, only skill counts","very little","about equally with skill","a lot","it decides it"]),
("When a friend asks for your honest opinion of their partner, what do you give?",["a blunt, logical assessment","an honest assessment with care","a balanced view","mostly positive things","only what will make them feel good"]),
("When you watch a debate, what wins you over?",["the tightest logic","the best evidence","a mix of logic and appeal","the most sincere speaker","the one who moves me most"]),
("How do you write a complaint to a company?",["a factual list of failures","facts with a clear demand","facts with a polite tone","a friendly note explaining how I felt","a gentle note that avoids blaming anyone"]),
("When grading a classmate's presentation for a peer review, how do you score it?",["strictly by the rubric","by the rubric with slight leniency","by the rubric and effort","mostly by effort","generously so they feel good"]),
("When you choose how to split an inheritance of family items, what guides you?",["equal value for everyone","clear rules everyone agrees on","fairness with some flexibility","what each item means to each person","whatever keeps the family closest"]),
("When your friend tells you about a conflict they had, how do you respond?",["I analyze who was in the wrong","I point out what they could have done better","I ask questions to see both sides","I validate how they feel","I take their side completely"]),
("When a pet owner asks if they should spend a lot on treatment, what do you consider?",["only the practical costs and odds","mostly costs and odds","costs and their attachment equally","mostly their attachment","only what their heart tells them"]),
("When arguing with someone you love, how do you argue?",["I stick to logic no matter what","I focus on logic but watch my tone","I balance logic and feelings","I focus on how we both feel","I drop the point to protect the bond"]),
("When a student in your study group is falling behind, what do you do?",["leave them to catch up alone","point them to resources","explain the material once","spend extra time encouraging them","rearrange the group to carry them"]),
("When your team has to choose a project name, what do you care about?",["clarity and precision","clarity with some appeal","both clarity and feel","how it makes people feel","what everyone is excited about"]),
("When a friend is clearly wrong in a trivia argument, what do you do?",["I prove them wrong on the spot","I correct them plainly","I correct them gently","I hint at the answer","I let them keep believing it"]),
("When making a hiring recommendation, how much do you weigh the candidate's personal story?",["not at all","slightly","moderately","heavily","it outweighs everything"]),
("When you comfort a friend after a breakup, what do you say?",["I list reasons it was for the best","I point out lessons to learn","I mix advice with comfort","I mostly listen and comfort","I just stay with them and share the sadness"]),
("When your club's budget has to be cut, how do you choose what goes?",["whatever has the lowest return","mostly by the numbers","numbers and member feelings equally","mostly by what members love least","whatever upsets the fewest people"]),
("When a relative asks your opinion on a risky investment, what do you share?",["a cold analysis of the risk","the main risks","risks and some encouragement","mostly encouragement","only support for their hopes"]),
("When you review a restaurant online, what do you mention?",["only the food and price facts","mostly facts with a verdict","facts and the atmosphere","mostly how it made me feel","only the feeling of the evening"]),
("When a friend repeatedly shows up late, how do you address it?",["I tell them it is disrespectful","I point out the pattern plainly","I mention it calmly once","I hint at it gently","I say nothing to avoid hurting them"]),
("When a coworker's idea is creative but impractical, how do you respond?",["I explain why it won't work","I list the practical problems","I suggest how to make it practical","I praise the creativity first","I support it to keep their spirits up"]),
("When deciding where to hold a family holiday, what matters most?",["the most practical location","cost and travel time","a balance of practicality and wishes","where people feel most welcome","wherever the eldest relatives want"]),
]
NN=[
"Do you usually check the facts before sympathizing with a friend's complaint?",
"Do you tend to soften criticism even when it makes the message less clear?",
"Do you usually decide who to side with based on who has the better argument?",
"Do you often put yourself in the other person's place before judging them?",
"Do you tend to rank options by pros and cons rather than by how they feel?",
"Do you usually feel the mood of a room before you consider what is being said?",
"Do you prefer a boss who is fair over one who is warm?",
"Do you often agree to something because saying no would upset someone?",
"Do you usually point out mistakes in plans made by people you like?",
"Do you tend to give people second chances because of their circumstances?",
"Do you find emotional arguments less convincing than logical ones?",
"Do you usually ask how someone feels before asking what happened?",
"Do you apply the same rules to friends and strangers?",
"Do you often let someone's disappointment change your decision?",
"Do you usually pick the most efficient option even if it annoys people?",
"Do you tend to worry more about hurting someone than about being wrong?",
"Do you usually enjoy finding the flaw in a well-loved idea?",
]
