N_="self.personality.type.jp"
C=[
("When you go grocery shopping, which is more like you?",[("fixed_list","shop from a fixed list"),("browse_and_decide","browse and decide in the store")]),
("When you pack for a weekend away, what do you do?",[("pack_early","pack a day or more ahead"),("pack_last_minute","throw things in right before you leave")]),
("When a friend asks you to pick a movie for tonight, which do you prefer?",[("pick_now","choose it now and lock it in"),("decide_later","decide when you sit down")]),
("When you rent a car on holiday, how do you plan the drive?",[("set_route","set the route and stops in advance"),("see_where","see where the road takes you")]),
("When a professor gives an open-ended assignment, how do you feel?",[("want_rubric","you want a clear rubric"),("enjoy_freedom","you enjoy the freedom")]),
("When you are cooking dinner, which is more like you?",[("decided_in_morning","dinner was decided in the morning"),("decide_at_fridge","you decide while looking in the fridge")]),
("When you start a new book while another is unfinished, how do you feel?",[("uneasy","uneasy leaving the first one open"),("fine","fine juggling several at once")]),
("When you arrive at an airport, which is more like you?",[("early_and_settled","very early and settled at the gate"),("just_in_time","just in time, heading straight to board")]),
("When you plan a birthday dinner for a friend, how do you handle it?",[("book_ahead","book a table well ahead"),("find_a_spot","find somewhere on the night")]),
("When you go to a buffet, what do you do?",[("survey_then_plan","survey everything and plan your plate"),("grab_as_you_go","grab what looks good as you go")]),
("When you are asked to pick a date for a meeting weeks away, what do you do?",[("commit_now","commit to a date now"),("keep_flexible","suggest keeping it flexible")]),
("When you decorate your home, how does it happen?",[("design_plan","you design a plan first"),("evolves_over_time","it evolves as you find things")]),
("When your team has a free-form brainstorm, how do you feel?",[("want_agenda","you want an agenda and an outcome"),("enjoy_wandering","you enjoy the wandering")]),
("When you decide on a summer project, how do you begin?",[("schedule_it","draw up a schedule"),("dive_in","dive in and see how it goes")]),
("When you are on a day trip and see an interesting detour, what do you do?",[("stick_to_plan","stick to the plan"),("take_detour","take the detour")]),
("When you choose what to wear for the week, which is more like you?",[("plan_outfits","plan outfits ahead"),("pick_each_morning","pick each morning by mood")]),
("When you are working on a paper, how do you handle the outline?",[("outline_first","write a full outline first"),("write_and_shape","write and let the shape emerge")]),
("When a store sale ends tomorrow, how do you shop?",[("decided_already","you already know what you are buying"),("browse_and_see","you browse and see what catches your eye")]),
("When a friend texts asking if you are free now, what do you usually say?",[("already_booked","you already have plans set"),("sure_lets_go","sure, you are open to it")]),
("When you set up a new job, what do you create in your first week?",[("systems","systems, folders, and routines"),("nothing_fixed","nothing fixed, you adapt as work comes")]),
("When there are several ways to reach a goal, which is more like you?",[("pick_and_commit","pick one and commit early"),("try_several","try several and keep switching")]),
("When you host friends for dinner, how does the menu get decided?",[("days_before","days before, with a shopping list"),("on_the_day","on the day, by what's around")]),
("When a hiking trail has several branches, what do you do?",[("follow_the_map","follow the route you mapped"),("pick_on_whim","pick whichever looks nice")]),
("When you finish work on a Friday, which is more like you?",[("weekend_mapped","your weekend is already mapped out"),("weekend_open","your weekend is wide open")]),
("When you take a class, which schedule do you prefer?",[("fixed_times","fixed times each week"),("self_paced","self-paced whenever you feel like it")]),
("When you start your morning, which is more like you?",[("same_routine","the same routine in the same order"),("varies_daily","it varies from day to day")]),
("When you choose a gift for a holiday, when do you buy it?",[("weeks_ahead","weeks ahead"),("last_days","in the last few days")]),
("When you play a strategy game, which is more like you?",[("long_plan","follow a long-term plan"),("react_to_moves","react to what happens each turn")]),
("When a club you are in drafts a yearly calendar, how do you feel?",[("glad_structure","glad for the structure"),("prefer_loose","you would rather keep it loose")]),
("When your manager changes priorities midweek, how do you react?",[("unsettled","unsettled until a new plan is set"),("roll_with_it","you roll with it easily")]),
("When you are sorting out a messy drawer, which is more like you?",[("finish_in_one_go","finish it in one go"),("stop_and_return","stop halfway and come back whenever")]),
("When friends start planning a festival trip months ahead, what do you do?",[("book_early","book tickets and lodging early"),("wait_and_see","wait and see closer to the date")]),
("When your to-do list is done early in the day, what do you do?",[("plan_tomorrow","plan tomorrow's list"),("go_with_the_flow","go with whatever comes up")]),
("When you choose a restaurant on a trip, which is more like you?",[("researched_ahead","one you researched ahead"),("walk_in_somewhere","somewhere you stumble upon")]),
("When you have a big purchase to make, which is more like you?",[("decide_and_done","decide and be done with it"),("keep_browsing","keep browsing options for a while")]),
("When your study group sets a meeting time, how do you prefer it?",[("fixed_weekly","fixed each week"),("arranged_each_time","arranged each time")]),
("When you enter a long weekend, which feels better?",[("each_day_planned","each day has a plan"),("nothing_planned","nothing is planned")]),
("When you write emails, which is more like you?",[("clear_inbox","reply and clear the inbox promptly"),("leave_open","leave some open until you feel like answering")]),
("When a road trip has an overnight stop, how do you handle lodging?",[("book_in_advance","book it in advance"),("find_on_arrival","find a place when you arrive")]),
("When you are handed a new board game with loose rules, which do you prefer?",[("settle_rules","settle the house rules before starting"),("figure_out_playing","figure them out while playing")]),
("When your friend changes the restaurant on the way there, how do you feel?",[("thrown_off","thrown off"),("happy_to_switch","happy to switch")]),
("When you plan to learn an instrument, which is more like you?",[("practice_schedule","set a practice schedule"),("play_when_inspired","play whenever inspired")]),
("When a vacation day has no plans yet, how do you start it?",[("make_plan_at_breakfast","make a plan at breakfast"),("wander_out","wander out and see")]),
]
S=[
("How do you usually handle bills that arrive in the mail?",["I pay them the day they arrive","I pay them within a set schedule","I pay them when I remember, before the due date","I pay them near the due date","I often pay them late after a reminder"]),
("How do you plan a weekday evening?",["every hour is scheduled","the main activity is set in advance","I have a rough idea","I decide when I get home","I let it unfold with no plan"]),
("When a trip's itinerary has free days, how do you feel?",["anxious until I fill them","I pencil in options right away","I plan a little and leave some open","I enjoy leaving them open","I hope the whole trip is free days"]),
("How do you approach a new work week?",["I plan each day in detail","I set daily priorities","I set a few goals for the week","I take things as they come with a rough goal","I don't plan the week at all"]),
("When a group dinner is being arranged, when do you want the venue confirmed?",["weeks before","a few days before","the day before","the morning of","as we walk out the door"]),
("How do you keep track of appointments?",["a detailed calendar I check often","a calendar with most things in it","a few reminders on my phone","I mostly remember them","I often forget until someone reminds me"]),
("When you start a hobby project like building a shelf, how do you proceed?",["I draw exact plans first","I sketch a plan and gather materials","I have a rough idea and start","I start and figure it out","I improvise from start to finish"]),
("When you have a free day off work, how is it decided?",["planned in detail days ahead","planned the night before","a loose plan in the morning","decided hour by hour","decided entirely by mood"]),
("When a friend suggests changing tonight's plans, how do you respond?",["I resist and keep the original plan","I agree only if it's a clear improvement","I'm open to it","I'm happy to change","I love it and often suggest changes myself"]),
("How often do you reorganize your task list or planner?",["every day, carefully","several times a week","now and then","rarely","I don't keep one"]),
("How do you prepare for an exam or big test?",["I follow a study schedule set weeks ahead","I start early with a rough plan","I study steadily when I can","I cram in the last few days","I cram the night before"]),
("When a vacation rental offers flexible check-in times, what do you do?",["I set an exact arrival time right away","I pick a rough window ahead","I decide on the travel day","I show up when I show up","I don't even think about it"]),
("How do you treat a deadline set far in the future?",["I start immediately and finish early","I break it into steps with dates","I start somewhere in the middle","I start close to the deadline","I finish right at the deadline"]),
("When you go to a new city with no plans, how do you feel?",["very uneasy","a bit uneasy","fine","excited","thrilled by the freedom"]),
("How tidy is your planning for household chores?",["every chore has a set day","most chores have a routine","some chores have a routine","I do chores when I notice them","I do chores only when they pile up"]),
("When you go to a concert with friends, how do you arrange meeting up?",["a fixed time and place set in advance","a set time with a loose place","we agree on the day","we text as we arrive","we find each other somehow"]),
("When you decide on a class schedule for next term, when do you do it?",["the moment enrollment opens with a plan ready","soon after enrollment opens","within the enrollment period","near the end of enrollment","at the last possible moment"]),
("How much of your weekend is set by Friday?",["all of it","most of it","about half","very little","none of it"]),
("When a project plan exists, how closely do you follow it?",["exactly as written","closely with small tweaks","as a general guide","loosely","I mostly ignore it"]),
("How do you feel when a workday has no meetings or fixed tasks?",["lost without structure","a bit uneasy","neutral","pleased","delighted"]),
("When you have several errands, how do you do them?",["in a planned order with a set route","in a rough order","in whatever order is convenient","whenever I happen to pass by","I often forget some"]),
("When a big decision is pending, how long do you leave it open?",["I settle it immediately","I decide within a day or two","I take a reasonable time","I wait until I must","I keep it open even past when I should decide"]),
("When you plan a date night, how much is arranged ahead?",["everything down to the timing","dinner and activity booked","dinner booked only","a rough idea","nothing, we see what happens"]),
("When your routine is broken by a holiday, how do you feel?",["I rebuild a new routine right away","I keep parts of my routine","I adjust easily","I enjoy the break from routine","I hope routine never comes back"]),
("How do you handle unfinished tasks at the end of the day?",["I stay until they're done","I schedule them first thing tomorrow","I note them and move on","I leave them and see tomorrow","I forget about them entirely"]),
]
NN=[
"Do you usually know what you will eat for dinner before the afternoon?",
"Do you often start tasks before finishing the ones already underway?",
"Do you tend to buy tickets for events as soon as they go on sale?",
"Do you usually enjoy wandering without a destination?",
"Do you prefer to finalize holiday plans well before the holiday?",
"Do you often change your mind about weekend plans on the day?",
"Do you feel satisfied crossing items off a list?",
"Do you usually leave room in your schedule for surprises?",
"Do you tend to settle group plans yourself so they are fixed?",
"Do you often start a trip without knowing where you will sleep?",
"Do you usually plan your route before driving somewhere new?",
"Do you often decide what to wear only after seeing the weather that morning?",
"Do you usually keep a set bedtime on work nights?",
"Do you tend to wait for more options before choosing even when one is good enough?",
"Do you usually pack the night before an early departure?",
"Do you enjoy days where nothing is decided in advance?",
"Do you usually set a finish date for personal projects?",
]
