N_="self.personality.type.ei"
C=[
("At a wedding reception, where do you usually spend most of the evening?",[("dance_floor","on the dance floor or mingling between tables"),("home_table","at your own table with the people you came with")]),
("When a museum offers a guided group tour or an audio guide, which do you pick?",[("group_tour","the group tour with a live guide"),("audio_guide","the audio guide on your own")]),
("When you get a promotion, what do you want to do that evening?",[("gather_people","gather friends to celebrate"),("quiet_treat","enjoy a quiet treat on your own or with one person")]),
("When a neighbor waves you over for a chat on your way inside, what do you usually do?",[("stop_and_chat","stop and chat for a while"),("wave_and_go","wave back and keep heading in")]),
("When you are stuck on a work problem, where do you usually turn first?",[("ask_colleague","walk over and ask a colleague"),("work_it_alone","keep working it over on your own")]),
("Which kind of gym workout do you gravitate toward?",[("group_class","a group class with an instructor"),("solo_session","a solo session with headphones in")]),
("On a long hike, which do you prefer?",[("hiking_group","hiking with a chatty group"),("hiking_alone","hiking alone or in silence with one companion")]),
("When you have good news at the end of a workday, what do you do first?",[("call_someone","call or message someone right away"),("sit_with_it","sit with it quietly for a while first")]),
("At a networking event, which is more like you?",[("work_the_room","move around meeting as many people as you can"),("one_good_talk","find one person and talk with them most of the night")]),
("When your team goes out for drinks after work, what do you usually do?",[("join_and_stay","join and stay until late"),("skip_or_short","skip it or leave after one drink")]),
("When you start a new class, where do you tend to sit?",[("front_near_people","near others where you can chat"),("edge_seat","an edge seat where you can keep to yourself")]),
("Which kind of vacation leaves you more rested?",[("busy_resort","a lively resort full of people and events"),("remote_cabin","a remote cabin with little company")]),
("When you are feeling restless on a weeknight, what do you usually do?",[("find_company","text people to see who is around"),("solo_activity","start a solo project or go for a walk alone")]),
("On a flight, when the passenger beside you starts chatting, what do you usually do?",[("chat_back","chat back happily for much of the flight"),("polite_short","reply politely and then put on headphones")]),
("When you want to learn about a new city you have moved to, which approach do you take?",[("join_groups","join local clubs and meetups"),("explore_alone","explore neighborhoods on your own")]),
("When you have an hour before a meeting, which do you prefer?",[("chat_with_coworkers","chat with coworkers in the kitchen"),("quiet_desk","stay at your desk and settle your thoughts")]),
("In a team chat, which is more like you?",[("post_often","post often and react quickly"),("post_rarely","read along and post only when you have something considered")]),
("When a party is winding down, which role do you usually play?",[("last_to_leave","one of the last people still talking"),("early_exit","one of the first to slip out")]),
("When you have a big decision about a move, whose input do you seek first?",[("many_opinions","many friends and family, out loud"),("own_reflection","your own reflection, perhaps journaling")]),
("When you are introduced to a friend of a friend, which is more like you?",[("jump_in","jump into conversation right away"),("warm_up","hang back and warm up slowly")]),
("Which kind of creative project appeals to you more?",[("group_production","a group production like a play or band"),("solo_creation","a solo creation like writing or drawing")]),
("When a coworker invites you to eat lunch with a big group, what do you usually do?",[("join_the_group","join the group"),("eat_alone","thank them and eat alone")]),
("After finishing a hard exam, what do you usually want to do?",[("debrief_with_friends","talk it through with classmates"),("go_off_alone","go off on your own to unwind")]),
("At a family reunion, where do you usually end up?",[("center_of_it","in the middle of the loudest conversation"),("side_room","in a quieter corner with one or two relatives")]),
("When a stranger at a bus stop comments on the weather, what do you usually do?",[("strike_up_talk","use it to start a longer conversation"),("brief_reply","give a brief reply and look away")]),
("Which weekend morning sounds better to you?",[("brunch_with_friends","a busy brunch with friends"),("slow_morning_alone","a slow morning alone with coffee")]),
("When you are excited about a book you are reading, what do you do?",[("tell_everyone","tell people about it constantly"),("keep_it_private","enjoy it privately")]),
("When you join a new sports team or club, which is more like you?",[("social_first","get to know everyone quickly"),("activity_first","focus on the activity and let friendships come slowly")]),
("When a coworker stops by your desk to vent, how do you usually feel?",[("energized","glad for the company"),("interrupted","a little drained by the interruption")]),
("Which kind of birthday do you prefer for yourself?",[("big_party","a big party with lots of guests"),("small_dinner","a small dinner or a day to yourself")]),
("When you are in a waiting room, which is more like you?",[("talk_to_others","chat with others waiting"),("keep_to_yourself","read or scroll quietly")]),
("When you are planning a free afternoon, which pulls you more?",[("see_people","meeting someone for coffee"),("recharge_solo","doing something alone")]),
("When you are asked to present your idea, which format do you prefer?",[("live_discussion","talking it through live with the group"),("written_first","writing it up for people to read")]),
("When you finish a long solo project, what do you crave most?",[("company","company and conversation"),("more_quiet","more quiet time to rest")]),
("When a big group chat is buzzing all evening, which is more like you?",[("in_the_thick","jump in and keep the chat going"),("mute_it","mute it and catch up later")]),
("During a road trip with friends, which seat suits you best?",[("front_talking","up front keeping the conversation going"),("back_quiet","in the back with music or a window view")]),
("When you are nervous before a job interview, what calms you down?",[("talk_to_friend","talking to a friend right before"),("quiet_prep","sitting quietly and going over your notes")]),
("When you sign up for a volunteer shift, which role appeals more?",[("greeting_people","greeting and talking with visitors"),("behind_the_scenes","sorting supplies behind the scenes")]),
("On a lunch break at a new job, which would you rather do?",[("eat_with_team","eat with the team to get to know them"),("walk_alone","take a walk alone to reset")]),
("When a friend asks what you have been up to, which is more like you?",[("long_update","give a long, lively update"),("short_update","give a short update and ask about them")]),
("Which setting helps you think most clearly?",[("buzz_of_people","a busy café with people around"),("silent_room","a silent room by yourself")]),
("When your plans for a quiet night in get replaced by a spontaneous party invite, how do you feel?",[("pleased","pleased to go out instead"),("disappointed","a little let down to lose the quiet night")]),
("When your team finishes a project, which kind of celebration appeals to you more?",[("team_outing","a team outing with everyone"),("personal_reward","a personal reward on your own time")]),
]
S=[
("When you get home after a full day of classes or work, what happens to your social energy?",["I need the rest of the evening completely alone","I want a quiet hour before seeing anyone","I am happy to chat with whoever is home","I look for people to call or see","I am already making plans to go back out"]),
("When a friend invites you to a crowded street festival, how do you respond?",["I turn it down and stay home","I go only if I can leave early","I go and stay for a while","I go and stay until it winds down","I go and try to bring more friends along"]),
("How do you spend the minutes before a class or meeting starts?",["I sit silently and avoid eye contact","I review my notes quietly","I chat with the person next to me if they start","I start conversations with the people nearby","I walk around greeting people"]),
("When you have a thought you are excited about, how do you develop it?",["I keep it to myself until it is fully formed","I write it down and share it much later","I share it with one close person","I talk it through with a few people","I bring it up with anyone who will listen"]),
("After a week of working entirely alone, how do you feel?",["I feel wonderfully rested","I feel fine and could keep going","I start missing people a bit","I feel restless and want company","I feel flat and drained without people"]),
("How do you usually spend your commute home?",["I keep headphones on and speak to no one","I sit quietly with my thoughts","I send a few messages to friends","I make a phone call to catch up","I chat with fellow commuters"]),
("When you are at a restaurant alone, how do you feel?",["I love it and do it often","I enjoy it now and then","I feel neutral about it","I feel a bit awkward","I avoid eating out alone"]),
("How do you treat an open seat next to you on a train?",["I hope it stays empty the whole way","I put my bag on it to discourage company","I let anyone sit and say nothing","I nod and make small talk if they sit","I often end up in a long chat with whoever sits"]),
("When friends plan a group holiday, how do you want to spend the days?",["mostly off on my own","some time with the group, a lot alone","an even mix of group and alone time","mostly with the group","every moment with the group"]),
("When your workplace moves to working fully from home, how do you react?",["I am delighted to be alone all day","I am mostly happy with it","I have mixed feelings","I miss the office buzz","I feel isolated and look for ways to see people"]),
("How do you usually react when your phone rings with a friend's name?",["I let it go and text back later","I answer but keep it short","I answer and chat a while","I answer happily and talk a long time","I pick up excitedly and suggest meeting"]),
("When you are in a group project, how do you prefer to split the work?",["I take a piece and do it entirely alone","I work alone and check in rarely","I mix solo work with team sessions","I prefer working side by side with others","I want to do everything together as a group"]),
("When you move into a shared apartment, how much time do you spend in common areas?",["I stay in my room almost always","I use common areas only when needed","I spend some evenings in shared spaces","I hang out in common areas most evenings","I am always in the shared space chatting"]),
("How do you feel about eating lunch with a table of people you barely know?",["I would find a way to eat alone","I would sit there but stay quiet","I would chat a little","I would enjoy getting to know them","I would try to become the heart of the table"]),
("On a Sunday with no plans, how many people do you end up seeing?",["no one at all","one person at most","a couple of people","a small group","as many as I can find"]),
("How do you prefer to share personal news like a new job?",["I tell almost no one","I tell only my closest person","I tell a handful of friends","I tell most of my friends","I announce it widely"]),
("When a gathering you host is ending, how do you feel?",["relieved to have my home back","glad it went well and ready for quiet","content either way","a bit sad it is ending","eager to keep it going somewhere else"]),
("How do you spend the break during a long workshop?",["I leave the room to be alone","I stay seated and check my phone","I chat with whoever is next to me","I find people to talk with","I work the room and meet new faces"]),
("How does being home alone on a Friday night feel to you?",["like a treat I look forward to","pleasant and relaxing","neither good nor bad","a little lonely","like a wasted Friday"]),
("When you are figuring out a new hobby, how much do you involve others?",["I learn it completely alone","I use books or videos on my own","I ask a friend now and then","I join a class with others","I only take it up if friends join me"]),
("How do you feel when a coworker suggests a daily team check-in call?",["I dread it","I tolerate it","I do not mind it","I like staying connected","I look forward to it each day"]),
("When you are waiting for a delayed flight, how do you pass the time?",["reading alone in a quiet corner","listening to something with headphones","calling someone to chat","talking with the people around me","organizing a group chat among stranded travelers"]),
("How often do you invite people over without a special reason?",["almost never","only on rare occasions","now and then","fairly often","all the time"]),
("When you visit a friend's workplace, how do you act around their coworkers?",["I stay in the background","I say a quick hello","I make friendly small talk","I chat and ask them about themselves","I end up chatting with everyone there"]),
("When you have been in meetings all morning, what do you want for lunch?",["total silence on my own","a quiet meal with no talking","a light chat with one person","lunch with a few coworkers","a lively group lunch"]),
]
NN=[
"Do you usually feel more energized walking out of a lively dinner party than walking in?",
"Do you often suggest a call instead of a text when making plans?",
"Do you usually stay behind after class or work to keep chatting?",
"Do you tend to plan alone time into your week on purpose?",
"Do you usually feel sharper after bouncing ideas off someone than after thinking alone?",
"Do you often put on headphones in public so no one starts a conversation?",
"Do you tend to call someone when you are bored?",
"Do you usually enjoy group dinners where you cannot hear everyone at once?",
"Do you often find a quiet spot to hide during big events?",
"Do you usually introduce yourself first when meeting new neighbors?",
"Do you prefer texting to calling so you can think before replying?",
"Do you usually look for a lively place to work, like a busy café?",
"Do you often feel the need to be alone after a long family visit?",
"Do you usually enjoy group phone calls with several friends at once?",
"Do you usually take the stairs to avoid small talk in the elevator?",
"Do you often end up the host because you like having people over?",
"Do you usually need a quiet moment before joining a party already in progress?",
]
