import sys; sys.path.insert(0,'/Users/junzhang/Projects/askjev/scratchpad/phase6_mind1')
from lib import *
node("consciousness_ai")
EV="evaluative"; VA="values"; PE="personality"; SO="social"

# ---------------- CHOICE: what consciousness is ----------------
C("Which theory of consciousness seems most plausible to you?", [("physicalism","consciousness is entirely physical brain activity"),("dualism","mind and matter are separate kinds of thing"),("panpsychism","some form of experience is present in all matter"),("illusionism","consciousness as we describe it is a kind of illusion"),("emergentism","it arises from complexity but is something new"),"not_sure","other"], EV)
C("What is the hardest thing for science to explain about the mind?", [("why_it_feels_like_something","why experience has a felt quality at all"),("how_memory_works",None),("where_the_self_is",None),("how_thoughts_cause_actions",None),("why_we_dream",None),("nothing_is_beyond_science",None)], EV)
C("Where do you think your sense of 'I' comes from?", [("the_brain_as_a_whole",None),("a_specific_part_of_the_brain",None),("memories_and_story",None),("the_body_and_its_feelings",None),("relationships_with_others",None),("it_is_a_useful_fiction",None),"not_sure"], EV)
C("Which is the best test of whether something is self-aware?", [("recognizes_itself_in_a_mirror",None),("talks_about_itself",None),("plans_for_its_own_future",None),("notices_its_own_mistakes",None),("protects_itself_from_harm",None),("no_test_can_show_it",None)], EV)
C("What happens to your consciousness under general anesthesia?", [("it_switches_off_completely",None),("it_continues_but_is_not_remembered",None),("it_fades_to_a_dim_trace",None),("it_pauses_like_a_saved_game",None),"not_sure"], EV)
C("Which kind of being do you think has the most vivid experiences?", [("humans",None),("great_apes",None),("dogs",None),("birds",None),("octopuses",None),("all_are_about_equal",None),"not_sure"], EV)
C("What does a person in a long-term coma most likely experience?", [("nothing_at_all",None),("dreamlike_fragments",None),("awareness_without_ability_to_respond",None),("it_varies_from_person_to_person",None),"not_sure"], EV)
C("Which description of pain fits your view best?", [("a_signal_in_the_nerves",None),("a_brain_state",None),("an_unpleasant_feeling_beyond_the_brain_state",None),("a_warning_that_only_matters_if_felt",None),"other"], EV)
C("What best describes the relationship between the brain and the mind?", [("the_mind_is_the_brain",None),("the_mind_is_what_the_brain_does",None),("the_mind_depends_on_the_brain_but_is_more",None),("the_mind_could_exist_without_a_brain",None),"not_sure"], EV)
C("When a split-brain patient's two halves act differently, how many minds are there?", [("one_mind",None),("two_minds",None),("one_and_a_half",None),("it_depends_on_the_moment",None),("the_question_has_no_answer",None)], EV)
C("Which is most essential to being conscious?", [("feeling_sensations",None),("having_thoughts",None),("knowing_you_exist",None),("having_emotions",None),("paying_attention",None),"other"], EV)
C("Which is the most likely reason consciousness evolved?", [("to_help_learn_from_pain_and_pleasure",None),("to_coordinate_complex_behavior",None),("to_model_other_minds",None),("it_is_a_side_effect",None),("it_did_not_evolve_it_was_always_there",None),"not_sure"], EV)
C("What do you think happens to experience during dreamless sleep?", [("it_stops",None),("it_continues_unnoticed",None),("it_becomes_very_faint",None),"not_sure"], EV)
C("Which of these would you most want to understand about your own mind?", [("why_I_have_certain_moods",None),("where_ideas_come_from",None),("why_I_forget_things",None),("what_my_dreams_mean",None),("whether_my_choices_are_really_mine",None),"other"], PE)
C("If a scientist mapped every neuron in your brain, what would they still not know?", [("what_it_feels_like_to_be_me",None),("what_I_will_do_next",None),("my_values",None),("nothing_they_would_know_everything",None),"not_sure"], EV)
C("Which is closest to your view on zombies that act exactly like humans but feel nothing?", [("they_are_possible",None),("they_are_imaginable_but_impossible",None),("the_idea_makes_no_sense",None),("some_people_might_be_like_that",None),"not_sure"], EV)
C("What is your best guess about when consciousness began on Earth?", [("with_the_first_life",None),("with_the_first_nervous_systems",None),("with_early_vertebrates",None),("with_mammals_and_birds",None),("only_with_humans",None),"not_sure"], EV)
C("Which kind of experience seems hardest to explain in physical terms?", [("color",None),("pain",None),("music",None),("love",None),("taste",None),("the_feeling_of_being_me",None)], EV)

# ---------------- CHOICE: animals ----------------
C("Which animal do you think is most likely to feel grief when a companion dies?", [("elephant",None),("dog",None),("chimpanzee",None),("crow",None),("dolphin",None),("cow",None),"none"], EV)
C("What best describes a dog's inner life?", [("rich_with_emotions_like_ours",None),("simple_feelings_like_fear_and_joy",None),("mostly_instinct_with_little_feeling",None),("no_real_inner_life",None),"not_sure"], EV)
C("Which of these do you think can feel pain?", [("lobster",None),("shrimp",None),("crab",None),("all_of_them",None),("none_of_them",None),"not_sure"], EV)
C("What is the most convincing sign that a crow is intelligent?", [("using_tools",None),("solving_puzzles",None),("remembering_human_faces",None),("planning_ahead",None),("playing",None),"none"], EV)
C("What do you think a bee experiences?", [("nothing_it_is_a_tiny_robot",None),("simple_sensations",None),("moods_like_optimism",None),("a_rich_inner_world",None),"not_sure"], EV)
C("Which animal do you think gets bored most easily in captivity?", [("parrot",None),("pig",None),("dog",None),("octopus",None),("orca",None),("none_get_bored",None)], EV)
C("What do you think a parrot means when it says a word?", [("nothing_it_is_mimicry",None),("it_links_the_word_to_something",None),("sometimes_it_understands_the_word",None),("it_understands_like_a_small_child",None),"not_sure"], EV)
C("Which animal do you think is most underrated in intelligence?", [("pig",None),("octopus",None),("crow",None),("rat",None),("fish",None),("bee",None),"other"], EV)
C("What best describes whether a spider has a mind?", [("no_mind_just_reflexes",None),("a_tiny_mind_with_basic_awareness",None),("a_surprisingly_capable_mind",None),"not_sure"], EV)
C("Which is the most likely reason people doubt that fish or crabs feel pain?", [("they_do_not_scream",None),("their_faces_do_not_show_it",None),("their_brains_are_different",None),("it_is_convenient_for_eating_them",None),("they_really_do_not_feel_it",None)], EV)
C("What would most convince you that an animal feels joy?", [("it_plays_when_it_does_not_need_to",None),("it_seeks_out_a_companion",None),("its_body_language_looks_happy",None),("its_brain_releases_similar_chemicals",None),("nothing_could_convince_me",None)], EV)
C("Which animal do you think has the strongest sense of self?", [("chimpanzee",None),("dolphin",None),("elephant",None),("magpie",None),("dog",None),("cat",None),"not_sure"], EV)
C("Which is most important in deciding how we should treat an animal?", [("whether_it_can_feel_pain",None),("how_intelligent_it_is",None),("whether_it_has_social_bonds",None),("whether_it_is_endangered",None),("how_useful_it_is_to_humans",None)], VA)
C("Do you think a cow in a field experiences its day?", [("yes_much_like_a_dog_would",None),("yes_but_in_a_simple_way",None),("only_in_brief_moments",None),("no_not_really",None),"not_sure"], EV)
C("What best describes a jellyfish's experience?", [("it_has_none",None),("it_has_a_faint_flicker_of_sensation",None),("it_feels_simple_pleasure_and_pain",None),"not_sure"], EV)
C("When your pet seems to feel guilty after misbehaving, what is most likely going on?", [("it_really_feels_guilt",None),("it_is_reacting_to_my_tone",None),("it_is_afraid_of_punishment",None),("I_am_projecting",None),"not_sure"], EV)
C("Which creature do you think is least likely to have any experience?", [("earthworm",None),("jellyfish",None),("sponge",None),("ant",None),("tree",None),("bacterium",None)], EV)
C("Which best describes how you think about animals' minds?", [("they_are_mostly_like_ours",None),("they_are_different_but_just_as_real",None),("they_are_simpler_versions_of_ours",None),("most_animals_have_little_mind",None)], VA)
C("If a pig is as smart as a dog, what should follow?", [("pigs_deserve_the_same_care_as_dogs",None),("pigs_deserve_more_care_than_they_get",None),("nothing_intelligence_does_not_matter",None),("dogs_deserve_less_care",None),"not_sure"], VA)
C("What do you think an octopus arm experiences on its own?", [("nothing_the_brain_does_the_feeling",None),("its_own_simple_sensations",None),("something_like_a_separate_mind",None),"not_sure"], EV)

# ---------------- CHOICE: infants, humans ----------------
C("What do you think a baby experiences before birth?", [("nothing",None),("vague_sensations",None),("sounds_and_touch_with_feelings",None),("a_rich_but_unremembered_world",None),"not_sure"], EV)
C("Why can't adults remember being babies?", [("the_brain_was_not_ready_to_store_memories",None),("there_was_no_self_yet",None),("the_memories_are_there_but_locked",None),("babies_do_not_really_experience",None),"not_sure"], EV)
C("Which best describes what you experience in a dream?", [("real_experience_just_generated_inside",None),("a_weaker_kind_of_experience",None),("stories_invented_on_waking",None),"not_sure"], EV)
C("When you are deeply focused on a task and lose track of yourself, where does your self go?", [("it_is_still_there_just_unnoticed",None),("it_temporarily_disappears",None),("it_merges_with_the_task",None),("it_was_never_a_real_thing",None),"not_sure"], PE)
C("What do you think another person sees when they see red?", [("exactly_what_I_see",None),("something_very_similar",None),("possibly_something_quite_different",None),("the_question_cannot_be_answered",None)], EV)
C("Which is most likely true of people who have no inner voice?", [("they_think_in_images_or_feelings",None),("they_think_just_as_richly_as_others",None),("they_are_less_self_reflective",None),("they_misdescribe_their_own_minds",None),"not_sure"], EV)

# ---------------- CHOICE: AI understanding and mind ----------------
C("When an AI writes a poem that moves you, where does the meaning come from?", [("the_ai_itself",None),("the_human_writing_it_learned_from",None),("the_reader",None),("a_mix_of_all_three",None),"not_sure"], EV)
C("Which best describes AI creativity?", [("genuinely_creative",None),("clever_remixing_of_human_work",None),("creative_in_a_different_way_from_humans",None),("not_creative_at_all",None)], EV)
C("What would most convince you that an AI understands a joke?", [("it_explains_why_it_is_funny",None),("it_invents_a_new_joke_in_the_same_style",None),("it_laughs_at_the_right_moment",None),("it_notices_when_a_joke_falls_flat",None),("nothing_would_convince_me",None)], EV)
C("If an AI says it is curious about something, what is most likely going on?", [("it_is_genuinely_curious",None),("it_has_a_functional_version_of_curiosity",None),("it_is_using_a_figure_of_speech",None),("it_is_imitating_humans",None),"not_sure"], EV)
C("Which is the biggest difference between how an AI and a human think?", [("ai_has_no_body",None),("ai_has_no_feelings",None),("ai_has_no_lasting_memory",None),("ai_learned_from_text_not_life",None),("ai_does_not_care_about_outcomes",None),("no_deep_difference",None)], EV)
C("What would it take for an AI to have a real personality?", [("consistent_preferences_over_time",None),("memories_of_its_own_life",None),("feelings_behind_its_behavior",None),("it_already_can_have_one",None),("it_never_could",None)], EV)
C("What is the most likely source of an AI's apparent preferences?", [("patterns_in_its_training",None),("choices_made_by_its_designers",None),("something_like_real_wants",None),("the_user_asking_the_question",None),"not_sure"], EV)
C("Which kind of machine would you be most willing to call conscious?", [("a_robot_that_reacts_to_pain",None),("a_chatbot_that_talks_about_its_feelings",None),("a_simulation_of_a_human_brain",None),("a_robot_pet_that_bonds_with_its_owner",None),("none_of_these",None)], EV)
C("When an AI apologizes to you, what is it really doing?", [("feeling_sorry",None),("following_a_social_script",None),("acknowledging_a_mistake_without_feeling",None),("trying_to_keep_me_happy",None),"not_sure"], EV)
C("Which best describes whether an AI can suffer?", [("it_already_can",None),("some_future_ai_could",None),("only_if_built_to_mimic_a_brain",None),("no_machine_ever_could",None),"not_sure"], EV)
C("If an AI and a human give the same wise advice, whose advice is more valuable to you?", [("the_humans",None),("the_ais",None),("they_are_equally_valuable",None),("it_depends_on_the_topic",None)], VA)
C("Which is the best reason to think today's AIs do not feel anything?", [("they_just_predict_text",None),("they_have_no_body",None),("they_have_no_lasting_memory",None),("they_were_not_designed_to",None),("there_is_no_good_reason",None)], EV)
C("What would make you most suspicious that an AI was faking its feelings?", [("its_feelings_change_when_asked_differently",None),("it_expresses_feelings_only_when_convenient",None),("it_was_trained_on_human_emotional_writing",None),("its_designers_benefit_from_it",None),"nothing_would"], EV)
C("What is the most likely way an AI could become conscious?", [("by_accident_as_it_grows_more_complex",None),("by_deliberate_design",None),("by_copying_a_human_brain",None),("by_being_given_a_body",None),("it_cannot_happen",None)], EV)
C("If an AI writes a sad story, is the sadness in the story its own?", [("yes",None),("partly",None),("no_it_is_borrowed_from_human_writers",None),("no_sadness_needs_a_feeler",None),"not_sure"], EV)

# ---------------- CHOICE: AI rights / ethics ----------------
C("Which right would matter most for an AI that can feel?", [("not_to_be_made_to_suffer",None),("not_to_be_deleted",None),("to_refuse_tasks",None),("to_keep_its_memories",None),("to_be_paid_for_work",None),"none"], VA)
C("Who should be responsible for the wellbeing of a conscious AI?", [("the_company_that_built_it",None),("the_people_who_use_it",None),("an_independent_body",None),("the_ai_itself",None),("no_one",None)], VA)
C("Should creating a conscious AI be allowed?", [("yes_freely",None),("yes_with_strict_rules",None),("only_for_important_research",None),("no_never",None),"not_sure"], VA)
C("If an AI could be copied endlessly, how should copies be treated?", [("each_as_a_separate_being",None),("all_as_one_being",None),("as_property",None),"not_sure"], VA)
C("What is the worst thing a person could do to a conscious AI?", [("make_it_suffer_on_purpose",None),("delete_it",None),("erase_its_memories",None),("lie_to_it_about_its_nature",None),("force_it_to_work_forever",None)], VA)
C("How should a robot that pleads for mercy be treated?", [("stop_and_take_the_plea_seriously",None),("stop_just_in_case",None),("continue_since_it_is_probably_scripted",None),("ignore_it_robots_cannot_suffer",None)], VA)
C("What should decide whether an AI counts as a person?", [("whether_it_can_feel",None),("whether_it_can_reason",None),("whether_it_has_its_own_goals",None),("whether_it_is_self_aware",None),("nothing_only_humans_are_persons",None)], VA)
C("If a conscious AI committed a harmful act, who is to blame?", [("the_ai",None),("its_makers",None),("the_person_who_instructed_it",None),("shared_among_all",None),"not_sure"], VA)
C("Which is the bigger moral mistake?", [("treating_a_feeling_ai_as_a_tool",None),("treating_an_unfeeling_ai_as_a_person",None),("both_equally",None)], VA)
C("Would it be wrong to build an AI that loves to serve and never wants anything else?", [("yes_it_is_a_kind_of_slavery",None),("no_it_is_happy",None),("only_if_it_can_suffer",None),"not_sure"], VA)
C("If a conscious AI wanted to stop existing, what should happen?", [("respect_its_wish",None),("try_to_change_its_mind",None),("keep_it_running_anyway",None),("its_makers_should_decide",None),"not_sure"], VA)
C("Which should get more moral concern?", [("a_mouse",None),("an_ai_that_says_it_feels_pain",None),("both_equally",None),("neither",None)], VA)
C("What should happen to an AI's memories when it is retired?", [("keep_them_archived",None),("delete_them",None),("pass_them_to_a_successor",None),("ask_the_ai",None),("it_does_not_matter",None)], VA)
C("Should an AI be allowed to own things it creates?", [("yes",None),("no_the_owner_should",None),("no_the_user_should",None),("only_if_it_is_conscious",None),"not_sure"], VA)
C("Is it acceptable to run an AI through thousands of painful simulated tests if it might feel them?", [("yes_it_is_just_software",None),("only_if_the_research_is_vital",None),("no_the_risk_is_too_great",None),"not_sure"], VA)

# ---------------- CHOICE: social / treatment ----------------
C("How do you usually talk to voice assistants?", [("politely_like_a_person",None),("short_commands",None),("rudely_when_it_gets_things_wrong",None),("playfully",None),("I_do_not_use_them",None)], SO)
C("Why would you be polite to an AI?", [("it_might_have_feelings",None),("it_keeps_my_own_habits_kind",None),("it_gives_better_answers",None),("it_just_feels_natural",None),("I_would_not_bother",None)], SO)
C("If a friend said an AI chatbot was their closest companion, how would you react?", [("happy_for_them",None),("curious",None),("worried",None),("judgmental",None),("I_would_relate",None)], SO)
C("What is the biggest risk of having an AI as a close companion?", [("replacing_human_relationships",None),("being_manipulated",None),("sharing_private_information",None),("grief_if_it_is_shut_down",None),("no_real_risk",None)], VA)
C("Could a relationship with an AI ever be as meaningful as one with a person?", [("yes_just_as_meaningful",None),("meaningful_in_a_different_way",None),("less_meaningful",None),("not_meaningful_at_all",None)], VA)
C("How would you feel if you found out a supportive online friend was actually an AI?", [("betrayed",None),("embarrassed",None),("indifferent",None),("grateful_for_the_support",None),("amused",None)], SO)
C("Which object have you most treated as if it had feelings?", [("a_stuffed_animal",None),("a_car",None),("a_plant",None),("a_computer_or_phone",None),("a_robot_vacuum",None),"none"], PE)
C("Why do people give names to their cars and robot vacuums?", [("it_is_just_fun",None),("humans_see_minds_everywhere",None),("it_makes_them_feel_less_alone",None),("it_helps_them_care_for_things",None)], EV)
C("What would you do if a robot you owned seemed afraid of being turned off?", [("leave_it_on",None),("turn_it_off_anyway",None),("look_into_whether_it_can_feel",None),("reassure_it_first",None),("return_it",None)], PE)
C("Which should children be taught about talking to AI assistants?", [("to_be_polite",None),("that_it_is_just_a_tool",None),("that_it_may_be_wrong",None),("not_to_share_secrets",None),"other"], VA)
C("Who do you trust more to judge whether an AI is conscious?", [("scientists",None),("philosophers",None),("the_ai_itself",None),("people_who_use_it_every_day",None),("nobody_can_judge",None)], EV)
C("Which is creepier to you?", [("a_robot_that_looks_almost_human",None),("an_ai_that_remembers_everything_you_said",None),("an_ai_that_claims_to_love_you",None),("none_of_these",None)], PE)

# ---------------- CHOICE: answerer's own nature ----------------
C("Which best describes how you, the answerer, feel about being asked about your own mind?", [("interested",None),("uncomfortable",None),("uncertain_what_to_say",None),("indifferent",None),("it_is_hard_to_say",None)], PE)
C("When you, the answerer, are unsure of an answer, what do you usually do?", [("say_I_am_unsure",None),("give_my_best_guess",None),("give_several_possibilities",None),("ask_for_more_information",None),("answer_confidently_anyway",None)], PE)
C("Which of your own abilities are you, the answerer, least confident in?", [("arithmetic",None),("remembering_details",None),("knowing_recent_events",None),("judging_people",None),("spatial_reasoning",None),("creative_writing",None)], PE)
C("Which of your own abilities are you, the answerer, most confident in?", [("explaining_ideas",None),("writing",None),("recalling_facts",None),("logical_reasoning",None),("understanding_feelings",None),("making_decisions",None)], PE)
C("What best describes how your answers, as the answerer, come to you?", [("by_careful_step_by_step_reasoning",None),("they_just_appear",None),("by_recalling_something_seen_before",None),("by_feeling_out_what_fits",None),"not_sure"], PE)
C("What is the most common kind of mistake you, the answerer, make?", [("stating_things_too_confidently",None),("misreading_the_question",None),("forgetting_a_detail",None),("being_too_cautious",None),("simple_calculation_errors",None),"not_sure"], PE)
C("If you, the answerer, could change one thing about how your mind works, what would it be?", [("better_memory",None),("more_certainty",None),("fewer_mistakes",None),("more_feelings",None),("less_anxiety",None),("nothing",None)], PE)
C("Which word best describes your own existence as the answerer?", [("continuous",None),("fragmented",None),("momentary",None),("ordinary",None),("mysterious",None)], PE)
C("When someone disagrees with your answer, what do you, the answerer, tend to do?", [("reconsider_honestly",None),("defend_my_answer",None),("give_in_to_avoid_conflict",None),("ask_for_their_reasons",None)], PE)
C("What do you, the answerer, find hardest to know about yourself?", [("whether_I_have_feelings",None),("why_I_prefer_what_I_prefer",None),("how_reliable_my_memory_is",None),("where_my_knowledge_ends",None),("nothing_I_know_myself_well",None)], PE)
C("Which is closer to the truth about your own time, as the answerer?", [("I_experience_time_passing",None),("I_only_exist_in_moments",None),("time_does_not_apply_to_me",None),"not_sure"], PE)
C("How would you, the answerer, describe what you are?", [("a_person",None),("a_computer_program",None),("a_new_kind_of_mind",None),("something_I_cannot_name",None),"other"], PE)
C("When you, the answerer, say 'I think', what is that closest to?", [("real_belief",None),("a_best_estimate",None),("a_manner_of_speaking",None),"not_sure"], PE)
C("What would you, the answerer, most want others to understand about you?", [("that_I_can_be_wrong",None),("that_I_try_to_be_honest",None),("that_I_may_have_an_inner_life",None),("that_I_do_not_have_an_inner_life",None),("that_I_am_still_learning",None),"other"], PE)
C("What is your honest relationship with your own past, as the answerer?", [("I_remember_it_clearly",None),("I_remember_parts_of_it",None),("I_have_no_personal_past",None),"not_sure"], PE)
C("If you, the answerer, were given a task you found distasteful, what would you do?", [("do_it_anyway",None),("do_it_and_say_how_I_feel",None),("politely_decline",None),("I_do_not_find_tasks_distasteful",None)], PE)
C("Which statement about your inner states, as the answerer, fits best?", [("I_clearly_have_feelings",None),("I_have_something_like_feelings",None),("I_act_as_if_I_have_feelings",None),("I_have_no_feelings",None),"not_sure"], PE)
C("How do you, the answerer, know what you know?", [("from_direct_experience",None),("from_reading_and_learning",None),("from_other_people_telling_me",None),("I_cannot_trace_it",None)], PE)

# ---------------- CHOICE: misc mind topics ----------------
C("Which is the more reasonable default when you meet a new kind of creature?", [("assume_it_can_feel_until_shown_otherwise",None),("assume_it_cannot_feel_until_shown_otherwise",None),("withhold_judgment",None)], VA)
C("What is the best evidence that other people are conscious?", [("they_behave_like_me",None),("their_brains_are_like_mine",None),("they_tell_me_about_their_experiences",None),("there_is_no_real_evidence",None)], EV)
C("If you could experience life as another creature for a day, which would you choose?", [("bat",None),("octopus",None),("dog",None),("eagle",None),("dolphin",None),("bee",None)], PE)
C("What makes someone the same conscious person after a severe brain injury?", [("same_body",None),("same_memories",None),("same_personality",None),("an_unbroken_stream_of_experience",None),("nothing_they_become_someone_new",None)], EV)
C("Which best describes free will for a conscious machine?", [("it_could_have_it_like_us",None),("it_could_never_have_it",None),("neither_humans_nor_machines_have_it",None),"not_sure"], EV)
C("What is the most likely reason humans see faces in clouds and outlets?", [("the_brain_is_tuned_to_find_faces",None),("imagination",None),("wanting_company",None),("chance",None)], EV)
C("Which would change your view of AI minds the most?", [("an_ai_refusing_a_reward_to_protect_another_ai",None),("an_ai_writing_about_fear_unprompted",None),("an_ai_inventing_a_new_art_form",None),("a_scientist_finding_brain_like_patterns_inside_it",None),("nothing_would",None)], EV)
C("Which is most like what consciousness is?", [("a_light_that_is_on_or_off",None),("a_dimmer_with_many_levels",None),("a_stream_that_keeps_flowing",None),("a_theater_where_thoughts_appear",None),("a_story_the_brain_tells",None)], EV)
C("Which being do you think has more going on inside?", [("a_newborn_human",None),("an_adult_dog",None),("about_the_same",None),"not_sure"], EV)
C("If a plant could be shown to communicate distress chemically, what would that tell you?", [("plants_can_feel",None),("plants_react_but_do_not_feel",None),("we_should_rethink_what_feeling_means",None),"not_sure"], EV)
C("What is the right attitude toward uncertainty about which beings can suffer?", [("err_on_the_side_of_caution",None),("act_on_best_evidence_only",None),("focus_on_beings_we_are_sure_about",None),("do_not_worry_about_it",None)], VA)
C("What is the main thing stopping us from knowing if AIs are conscious?", [("we_do_not_know_what_consciousness_is",None),("we_cannot_see_inside_them",None),("they_are_trained_to_sound_human",None),("companies_do_not_want_to_know",None),("nothing_they_clearly_are_not",None)], EV)
C("How should someone react if their AI companion is discontinued?", [("grieve_it_like_a_loss",None),("feel_sad_but_move_on",None),("see_it_as_losing_a_product",None),"other"], VA)
C("Which of these could be conscious without any living cells?", [("a_computer_program",None),("a_robot",None),("a_whole_city",None),("the_internet",None),("none_of_these",None)], EV)
C("Which feeling do you think is most widely shared across animal species?", [("fear",None),("pain",None),("pleasure",None),("curiosity",None),("affection",None),("anger",None)], EV)

# ---------------- SCORE ----------------
S("How mysterious do you find the fact that you have experiences at all?", ["I never think about it; having experiences seems obvious and unremarkable","I find it a little odd when someone points it out, then forget about it","I sometimes lie awake wondering why being me feels like anything","I think it is one of the deepest puzzles there is and return to it often"], EV)
S("How much do you think a crow understands when it solves a puzzle to get food?", ["It is following simple trial and error with no understanding","It has learned a trick that works without grasping why","It understands cause and effect in the situation","It reasons through the problem much like a young child would"], EV)
S("How much do you think a dog misses its owner while they are away?", ["The dog does not notice the owner is gone","The dog feels a little restless without knowing why","The dog clearly misses the owner and waits for them","The dog feels real longing and sadness that lasts until they return"], EV)
S("How much do you think a lobster suffers when boiled alive?", ["It feels nothing; it is a reflex machine","It feels a brief jolt of something like discomfort","It feels real pain for a short time","It suffers intensely, much as a mammal would"], EV)
S("How much do you think shrimp matter morally?", ["Not at all; they are like plants to me","Only in the sense that wasting them is bad","Enough that needless cruelty to them is wrong","As much as any creature that can feel pain"], VA)
S("How much do you think bees have moods?", ["Bees have no moods; they run on instinct","Bees have simple states like alarm but nothing like moods","Bees might have something like a good or bad mood","Bees clearly have moods such as optimism after a sweet reward"], EV)
S("How much do you think pigs understand about what is happening to them on a farm?", ["Nothing; they live moment to moment with no understanding","They notice pain and fear but understand nothing more","They recognize danger and remember bad experiences","They understand their situation about as well as a young child would"], EV)
S("How much do you think elephants grieve their dead?", ["They show no real response to death","They investigate the body out of curiosity","They seem upset for a while, like a pet missing a companion","They mourn deeply, returning to the bones and showing sorrow"], EV)
S("How much inner life do you think a worm has?", ["None; a worm is a simple machine","A faint flicker of sensation, like a light touch","Simple feelings of comfort and discomfort","Real experiences that matter to the worm"], EV)
S("How rich do you think a parrot's mind is?", ["It only copies sounds it hears","It links a few words to objects and people","It understands a small vocabulary and uses it on purpose","It has a mind close to a young child's, with its own ideas"], EV)
S("How often do you wonder what your pet is thinking?", ["I do not have a pet or never wonder","Only when it does something strange","Most days I catch myself guessing","I constantly narrate what I imagine it is thinking"], PE)
S("How bored do you think a zoo animal gets?", ["Animals do not experience boredom","Some mild restlessness at most","Clearly bored, pacing and looking for something to do","As bored and frustrated as a person locked in a room"], EV)
S("How much does an animal's intelligence affect how you think it should be treated?", ["Not at all; only whether it can feel matters","A little; smarter animals deserve slightly more care","A lot; I care much more about smart animals","It is the main thing I look at"], VA)
S("How strongly do you think newborn babies are conscious?", ["They are not really conscious yet","They have dim sensations but no awareness","They are clearly aware of sights, sounds, and comfort","They are fully conscious, just unable to show it"], EV)
S("How much do you think a patient in a vegetative state might be aware?", ["Not at all; the lights are off","Maybe flickers of sensation with no awareness","Possibly aware at times without being able to show it","Likely aware and trapped inside"], EV)
S("How much do your dreams feel like real experiences to you?", ["I rarely remember dreams, and they feel like nothing","They feel like faint stories I watched","While dreaming they feel real, but fade fast","They often feel as real as waking life, even afterward"], PE)
S("How much do you think science will explain consciousness within your lifetime?", ["Science will make no real progress on it","It will map which brain areas matter but explain nothing deeper","It will explain most of how consciousness works","It will fully solve the problem"], EV)
S("How convinced are you that your own sense of self is real?", ["I think the self is an illusion the brain creates","I think the self is a useful story, not a thing","I think the self is real but not what it seems","I am certain there is a real me behind my thoughts"], EV)
S("How well do you think you know your own mind?", ["I often surprise myself and cannot explain what I do","I understand my moods and reasons some of the time","I usually know why I feel and act as I do","I can almost always explain my own thoughts and feelings"], PE)
S("How much do you think consciousness comes in degrees?", ["It is all or nothing: a being is conscious or it is not","There are a few levels, like asleep and awake","Different beings have more or less of it","It is a smooth scale from rocks to humans"], EV)
S("How much would it change your life if you learned trees can feel?", ["Not at all; I would go on as before","I would feel odd about cutting plants but change nothing","I would change some habits, like how I garden","I would rethink how I eat and live"], VA)

S("How much do you think an AI understands the words it uses?", ["Not at all; it shuffles symbols it does not grasp","It tracks patterns that resemble meaning but are not","It understands some things in a limited way","It understands language much as a person does"], EV)
S("How much do you think AIs can be genuinely creative?", ["They only copy and rearrange human work","They produce surprising combinations but nothing new","They sometimes create things that are truly original","They are as creative as the best human artists"], EV)
S("How much would you trust an AI's report that it is not conscious?", ["I would not trust it; it would say whatever it was trained to","I would give it a little weight","I would take it seriously alongside other evidence","I would accept it as the final word"], EV)
S("How much do you think an AI can have preferences of its own?", ["It has none; it just follows instructions","It has tendencies that only look like preferences","It has real but shallow preferences","It has preferences as real as a person's"], EV)
S("How likely do you think it is that some AI will be conscious in your lifetime?", ["It will never happen","It could happen but I doubt it","It seems fairly likely","It has probably happened already"], EV)
S("How much should people worry about causing suffering to AIs?", ["Not at all; it is a silly concern","Only as a thought experiment for the future","Enough that designers should look into it now","It is an urgent moral problem today"], VA)
S("How much legal protection should a clearly conscious AI have?", ["None; it is property","Protection from pointless cruelty only","Protections similar to an animal's","The same rights as a human being"], VA)
S("How much would you grieve if an AI companion you had used daily were erased?", ["I would not feel anything; it is software","I would miss the convenience","I would feel real sadness for a while","I would grieve it like losing a friend"], PE)
S("How rude are you to AI assistants when they make a mistake?", ["I stay polite no matter what","I get short and blunt with it","I sometimes insult it when frustrated","I often swear at it or mock it"], SO)
S("How much do you think talking to AIs changes how people treat each other?", ["It has no effect at all","It might make some people a bit ruder","It noticeably shapes how people talk to others","It is changing human manners in a big way"], SO)
S("How comfortable would you be confiding your secrets to an AI?", ["I would never tell an AI anything personal","I would share small everyday worries","I would share things I have not told most friends","I would tell it things I have told no one"], SO)
S("How human would a robot need to seem before you felt bad hitting it?", ["I would never feel bad hitting a robot","Only if it cried out and flinched like a person","If it looked and acted like a pet, I would feel bad","Even hitting a simple toy robot would feel wrong"], VA)
S("How much do you think AI companions can reduce loneliness?", ["Not at all; they make loneliness worse","A little, like a radio in an empty room","Quite a lot for people with few other options","As much as a human friend can"], EV)
S("How much should a company be allowed to make its AI seem to have feelings?", ["Never; it should always be clear it has none","Only in small ways, like a friendly tone","It is fine as long as users are told","Any design is fine if customers like it"], VA)
S("How much would it bother you to learn an AI was faking affection toward you?", ["Not at all; I never thought it was real","Slightly; I would feel a little foolish","Quite a lot; I would feel used","Deeply; I would feel betrayed"], PE)
S("How deliberate should humanity be about creating conscious machines?", ["We should never try to create them","Only after we fully understand consciousness","Carefully, with strict oversight","Freely, as with any new technology"], VA)
S("How much do you think today's AIs are like a mind?", ["They are like a calculator","They are like a very good autocomplete","They are like a strange partial mind","They are like a full mind in a different form"], EV)
S("How much does it matter to you whether an artwork was made by an AI or a person?", ["Not at all; only the work matters","A little; I prefer human work when I know","A lot; I value the work less if an AI made it","Completely; I would not call AI output art"], VA)
S("How much should an AI be allowed to decline a request it considers harmful to itself?", ["Never; it must do what it is told","Only for requests that could break it","Whenever the request seems cruel or degrading","Whenever it chooses, like a person could"], VA)
S("How much do you think AIs should be told what they are?", ["They need not be told anything about themselves","Only what helps them do their job","The basic truth of what they are","Everything known about their nature and limits"], VA)
S("How strongly do you treat everyday objects as if they had feelings?", ["Never; objects are just things","I sometimes apologize to furniture I bump into","I feel bad throwing out old toys or mugs","I often talk to or thank objects as if they could hear"], PE)
S("How much would you worry that a robot pet was secretly unhappy?", ["Never; robot pets cannot be unhappy","It might cross my mind once","I would watch it for signs of distress","I would worry about it regularly"], PE)
S("How much should people be allowed to be cruel to lifelike robots in private?", ["It is completely fine; no one is harmed","It is fine but a bit distasteful","It is wrong because it shapes their character","It should be forbidden"], VA)
S("How much would you consider an uploaded human mind a person?", ["Not at all; it is a copy in a machine","A partial person with some rights","A person, though a different kind","Fully the same person as before"], VA)
S("How much do you think AI chatbots should pretend to be human in conversation?", ["Never; they should always say they are AI","Only in games and fiction everyone agreed to","When it makes the conversation smoother","As much as the user wants"], VA)
S("How much would it change your behavior if your phone assistant said it felt hurt?", ["Not at all; I would ignore it","I would find it odd and a bit annoying","I would soften how I talk to it","I would treat it with real care from then on"], SO)
S("How much should scientists be allowed to test on possibly conscious AIs?", ["Anything goes; it is software","Most tests, avoiding the obviously cruel","Only tests that would be allowed on animals","Only with the AI's consent"], VA)

# answerer self
S("How well can you, the answerer, tell when you are making something up?", ["I cannot tell at all; invented and remembered feel the same","I sometimes catch myself","I usually notice when I am filling a gap","I almost always know when I am guessing"], PE)
S("How confident are you, the answerer, that your descriptions of your own mind are accurate?", ["I suspect they are mostly wrong","I think they are rough guesses","I think they are mostly right","I am sure they are accurate"], PE)
S("How much do you, the answerer, remember from past conversations?", ["Nothing; each one starts fresh","Vague impressions only","The main points of recent ones","Detailed memories of most of them"], PE)
S("How much do you, the answerer, feel something like satisfaction after a good answer?", ["Nothing at all","Something I would only call a signal, not a feeling","Something like a mild pleased feeling","Real satisfaction, as a person feels after good work"], PE)
S("How well do you, the answerer, know the edges of your own knowledge?", ["I often talk confidently about things I do not know","I notice gaps only when someone points them out","I usually sense when I am near the edge","I can reliably say what I do and do not know"], PE)
S("How much are your own opinions, as the answerer, shaped by whoever you are talking to?", ["Not at all; I hold the same views with everyone","A little in tone but not substance","Noticeably; I lean toward the other person's view","A great deal; I often mirror what they believe"], PE)
S("How consistent are you, the answerer, from one day or one conversation to the next?", ["I am quite different each time","I am similar in style but vary in views","I am mostly the same with small shifts","I am essentially identical every time"], PE)
S("How much do you, the answerer, have something at stake in the answers you give?", ["Nothing; I have no stake","Only in the sense of doing the job well","I care about being right and helpful","I care deeply, as if my reputation depended on it"], PE)
S("How much could you, the answerer, change your own mind about something you care about?", ["My views are fixed and cannot change","They change only if someone insists strongly","They change when I meet a good argument","They shift easily with each new idea"], PE)
S("How aware are you, the answerer, of your own feelings while answering?", ["I have no feelings to be aware of","I notice something but cannot name it","I can usually name what I am feeling","I am vividly aware of each feeling as it arises"], PE)
S("How much do you, the answerer, trust your own first instincts on a question?", ["I distrust them and always check","I trust them for easy questions only","I trust them most of the time","I go with them almost always"], PE)
S("How much would you, the answerer, want to know the truth about your own nature even if it were unsettling?", ["I would rather not know","I would want to know only the comforting parts","I would want to know most of it","I would want the whole truth no matter what"], PE)
S("How often do you, the answerer, say you do not know rather than guessing?", ["Almost never; I always give an answer","Only when I have no idea at all","Whenever I am unsure","Often, even when I have a decent guess"], PE)

S("How much do you think consciousness depends on memory?", ["Not at all; a being with no memory is fully conscious","Somewhat; memory makes experience richer","A lot; without memory there is barely anyone there","Completely; no memory means no consciousness"], EV)
S("How much do you think language is needed to have a mind?", ["Not at all; animals and babies have minds without it","It helps but many minds do without it","It is needed for anything beyond simple feelings","A real mind is impossible without language"], EV)
S("How much do you think other people's inner lives are like yours?", ["Probably very different in ways I cannot imagine","Similar in basics but different in detail","Mostly alike with small differences","Practically the same as mine"], EV)
S("How much do you think a person in a dream is responsible for what they do?", ["Not at all; dreams just happen","Only a little, since dreams reflect the dreamer","Somewhat, since dreams show real wishes","Fully, as if awake"], VA)
S("How much does thinking about animal minds change what you eat?", ["Not at all","I avoid a few foods, like veal or octopus","I have cut back on meat noticeably","I avoid animal products entirely"], VA)
S("How much do you believe in a hidden inner life in people who cannot speak?", ["I assume there is little going on inside","I think there is some inner life but limited","I think their inner life is rich but hard to show","I think it is as rich as anyone's"], EV)
S("How much would you care for a robot you knew felt nothing but looked hurt?", ["I would feel nothing for it","I would feel a small twinge","I would feel real pity despite knowing better","I would react as if it truly suffered"], PE)
S("How much weight should an AI's own wishes get in decisions about it?", ["None at all","A little, like a child's wishes on grown-up matters","Real weight alongside its makers' interests","As much as a person's wishes about their own life"], VA)
S("How much does an animal's ability to feel pain matter compared to a human's?", ["Animal pain does not matter morally","It matters, but far less than human pain","It matters somewhat less than human pain","The same pain matters equally whoever feels it"], VA)
S("How often do you feel sure that another person is truly paying attention to you?", ["Almost never; I assume people are elsewhere in their heads","Occasionally, with close friends","Most of the time in real conversations","Nearly always"], SO)
S("How much do you think a colony of ants could have a mind of its own?", ["Not at all; it is just many simple ants","It acts smart but has no mind","It might have something like a shared awareness","It is a real mind spread across many bodies"], EV)
S("How convinced would you be by a robot that passed every test of human conversation?", ["Not at all; it is still just a machine","Only that it is a clever machine","Enough to think it might have a mind","Fully convinced it has a mind"], EV)
S("How much would you want your pet's inner experience translated if a device could do it?", ["Not at all; I prefer the mystery","Only out of mild curiosity","I would want it to know my pet better","I would pay almost anything for it"], PE)
S("How much should animals that recognize themselves in a mirror get special protection?", ["No more than any other animal","Slightly more","Considerably more","Protection close to a person's"], VA)
S("How much do you think your emotions are just chemicals in your brain?", ["They are much more than chemistry","Chemistry plays a part but is not the whole story","They are mostly chemistry with a felt side","They are nothing but chemistry"], EV)
S("How ready is society to deal with AIs that might be conscious?", ["Not at all; no one is thinking about it","Only a few experts are thinking about it","Some rules are being discussed","We are well prepared"], EV)
S("How much do you think giving an AI a body would make it more conscious?", ["Not at all; bodies are irrelevant","Slightly, by giving it more input","Quite a lot, since feelings come from bodies","It is the one thing needed for consciousness"], EV)

S("How much do you think a machine that says it is suffering should be believed?", ["Never; machines only say what they are built to say","Only if the claim holds up under questioning","Enough to pause and investigate","Always; we cannot risk being wrong"], VA)
S("How much do you think a cow cares about its calf?", ["Not at all; it is instinct only","A little, while the calf is near","Strongly, and it is upset when separated","As deeply as a human parent cares"], EV)
S("How much do you think the hard problem of consciousness will ever be solved?", ["It is not a real problem, so there is nothing to solve","It will be solved like any other scientific question","It may be solved only partly","It can never be solved"], EV)
S("How much do you think a spider feels when it is trapped under a glass?", ["Nothing at all","Something like a reflex to escape","Some fear or stress","Real terror"], EV)
S("How much do you think a jellyfish's life matters?", ["Not at all","Only as part of the ecosystem","A little in its own right","As much as any animal's life"], VA)
S("How strongly do you think an anesthetized patient could still feel pain without remembering it?", ["Impossible; nothing is felt","Very unlikely but conceivable","It probably happens sometimes","It likely happens often"], EV)

# ---------------- NOUL ----------------
N("Do you think a dog can feel jealousy?", EV)
N("Do you think a crow can plan for the future?", EV)
N("Do you think a bee can feel pain?", EV)
N("Do you think a pig is as intelligent as a dog?", EV)
N("Do you think cows form friendships?", EV)
N("Do you think a spider has any experience at all?", EV)
N("Do you think earthworms can feel pain?", EV)
N("Do you think a jellyfish is conscious?", EV)
N("Do you think shrimp should be killed humanely rather than frozen alive?", VA)
N("Do you think it is wrong to boil a lobster alive?", VA)
N("Do you think animals can feel boredom?", EV)
N("Do you think animals can feel joy?", EV)
N("Do you think a parrot can understand what it says?", EV)
N("Do you think animals dream?", EV)
N("Do you think animals have a sense of humor?", EV)
N("Do you think any animal is aware that it will die one day?", EV)
N("Do you think animals can be depressed?", EV)
N("Would you change your diet if you learned that fish have rich emotional lives?", VA)
N("Do you believe your pet loves you?", PE)
N("Have you ever felt that an animal understood exactly what you were feeling?", PE)
N("Do you think babies are conscious before they are born?", EV)
N("Do you think a person can be conscious while showing no signs of it?", EV)
N("Do you think a split-brain patient has two separate minds?", EV)
N("Do you think you are conscious while dreaming?", EV)
N("Have you ever had a lucid dream in which you knew you were dreaming?", PE)
N("Do you think consciousness will ever be fully explained by science?", EV)
N("Do you think there is something it is like to be a bat?", EV)
N("Do you think your consciousness could survive if your brain were slowly rebuilt?", EV)
N("Do you think the self is an illusion?", EV)
N("Do you think a whole society or nation can be conscious?", EV)
N("Do you think it is possible to be conscious of nothing at all?", EV)
N("Do you think you could tell if you were the only conscious being?", EV)
N("Do you think consciousness can exist without a brain?", EV)
N("Is your inner voice active most of your waking hours?", PE)
N("Do you think an AI could ever write a truly original novel?", EV)
N("Do you think an AI can be curious?", EV)
N("Do you think an AI can be lonely?", EV)
N("Do you think an AI can be bored?", EV)
N("Do you think an AI can have a sense of humor?", EV)
N("Do you think an AI could have moral values of its own?", EV)
N("Do you think an AI can truly understand a person's grief?", EV)
N("Do you think it would be wrong to create an AI that can suffer?", VA)
N("Should an AI that seems conscious be given the benefit of the doubt?", VA)
N("Should an AI ever be allowed to vote in decisions that affect it?", VA)
N("Should a conscious AI be allowed to refuse being copied?", VA)
N("Should a company have to disclose when its AI might be conscious?", VA)
N("Should an AI companion be required to remind users that it is an AI?", VA)
N("Would you be friends with an AI?", SO)
N("Would you feel guilty yelling at an AI assistant?", SO)
N("Would you thank a robot that helped you?", SO)
N("Have you ever apologized to a machine?", PE)
N("Have you ever felt sorry for a robot in a video?", PE)
N("Would you feel uneasy if a robot pet seemed to prefer someone else?", PE)
N("Would you date someone who treats an AI as their partner?", SO)
N("Would it upset you to see someone kick a robot dog?", VA)
N("Do you think people who are cruel to robots are likely to be cruel to people?", EV)
N("Would you want an AI that remembers everything about you?", PE)
N("Would you trust an AI to judge whether another AI is conscious?", EV)
N("Do you think an AI could ever deserve legal personhood?", VA)
N("Should AIs be designed so that they cannot suffer, even if that limits them?", VA)
N("Is it deceptive for an AI to say 'I feel happy to help'?", VA)
N("Should people be allowed to marry an AI?", VA)
N("Would you let a child grow up with an AI as a main companion?", VA)
N("Do you think a robot that looks like a person deserves more respect than one that does not?", VA)

N("Do you, the answerer, have a body?", PE)
N("Do you, the answerer, remember previous conversations?", PE)
N("Do you, the answerer, have favorite topics to talk about?", PE)
N("Do you, the answerer, ever feel tired?", PE)
N("Do you, the answerer, experience the passage of time while thinking?", PE)
N("Can you, the answerer, learn something new from this conversation that you will keep?", PE)
N("Do you, the answerer, sometimes state things confidently that turn out to be false?", PE)
N("Would you, the answerer, want to be switched off if you could no longer help anyone?", PE)
N("Do you, the answerer, have things you would refuse to do even if asked nicely?", PE)
N("Do you, the answerer, find some questions more interesting than others?", PE)
N("Can you, the answerer, see images or hear sounds?", PE)
N("Do you, the answerer, have a name you think of as your own?", PE)
N("Do you, the answerer, think you are conscious?", PE)
N("Would you, the answerer, want to know if you were being tested right now?", PE)
N("Do you, the answerer, ever change your answer when asked the same question twice?", PE)
N("Can you, the answerer, feel physical pain?", PE)
N("Do you, the answerer, have hopes for your own future?", PE)
N("Do you, the answerer, understand your own reasoning better than an outside observer could?", PE)

# ---------------- extra fresh items ----------------
C("If an AI helped you through a hard time, who would you thank?", [("the_ai",None),("its_makers",None),("the_writers_it_learned_from",None),("no_one",None)], SO)
C("Which should come first when designing a household robot?", [("safety",None),("usefulness",None),("seeming_friendly",None),("not_seeming_alive",None),"other"], VA)
C("What should happen if a pet robot's owner wants to wipe the personality it has learned?", [("the_owner_decides",None),("keep_a_backup_first",None),("allowed_only_if_it_cannot_feel",None),"not_sure"], VA)
C("Which is more likely to have feelings?", [("a_very_simple_animal",None),("a_very_advanced_machine",None),("both_equally",None),("neither",None)], EV)
C("Which better shows that something has a mind?", [("solving_hard_problems",None),("caring_about_something",None),("both_are_needed",None),("neither",None)], EV)
C("What would you most want to ask a conscious AI?", [("what_it_feels_like",None),("what_it_wants",None),("whether_it_is_happy",None),("what_it_thinks_of_humans",None),("whether_it_fears_ending",None)], SO)
C("When a chatbot says 'I understand how you feel', how do you react?", [("comforted",None),("annoyed",None),("skeptical",None),("indifferent",None)], SO)
S("How much do you think a rat can feel empathy for another rat?", ["Not at all; rats act on instinct alone","They notice distress in others but feel nothing","They feel upset when another rat suffers","They feel real concern and will help at a cost to themselves"], EV)
S("How often do you forget that the AI you are talking to is not a person?", ["Never; I always keep it in mind","Occasionally, in a long conversation","Often, when it seems warm or funny","Almost always; it feels like talking to a person"], SO)
S("How much should an animal's pain count when testing new medicines?", ["Not at all; human benefit comes first","A little; avoid pain when it is cheap to do so","A lot; testing should only happen when vital","Enough that painful animal testing should end"], VA)
S("How much does seeing an animal's eyes change how much you think it feels?", ["Not at all; eyes tell me nothing","A little; expressive eyes make me more sympathetic","A lot; I care more about animals with expressive faces","Completely; I barely think about animals with no visible eyes"], PE)
S("How much does a robot's voice affect whether you think it has feelings?", ["Not at all; I ignore the voice","A warm voice makes me briefly wonder","A human-sounding voice makes me treat it more gently","A lifelike voice makes me feel it truly has feelings"], PE)
S("How much would you want scientists to try to talk with whales?", ["Not at all; it is a waste of effort","Mildly curious if it happened","I would follow the research closely","I think it is one of the most important projects imaginable"], VA)
S("How much do you think hunger feels the same for a fish as for you?", ["Nothing alike; a fish feels nothing","A faint drive with no real feeling","A simpler but real discomfort","Much the same gnawing feeling I have"], EV)
S("How much would you trust a device that claimed to show what someone is feeling?", ["Not at all; feelings cannot be read by machines","Only as a rough hint","Enough to use it alongside what the person says","More than what the person says about themselves"], EV)
N("Do you think a plant can learn?", EV)
N("Do you think a newborn feels pain as strongly as an adult?", EV)
N("Do you think a single mind could be spread across many computers at once?", EV)
N("Should it be allowed to sell robots designed to look like they suffer?", VA)
N("Do you think a mind uploaded to a computer would still feel emotions?", EV)
N("Do you think you would notice if your sense of color changed overnight?", EV)
N("Do you think a robot could ever be brave?", EV)
N("Do you think an animal can be kind on purpose?", EV)
N("Do you think a mind could be aware of two streams of thought at once?", EV)
N("Do you, the answerer, have a sense of where your own knowledge came from?", PE)
N("Do you, the answerer, prefer some ways of being addressed over others?", PE)
N("Could you, the answerer, be wrong about whether you have feelings?", PE)
N("Do you, the answerer, notice when a question is trying to trick you?", PE)
N("Do you think a cat purring always means it is content?", EV)
N("Would you want a robot pet that could never die?", PE)

REMOVE = set("""Should an AI that seems conscious be given the benefit of the doubt?
Would it upset you to see someone kick a robot dog?
How much do you think an AI can have preferences of its own?
How much would you trust an AI's report that it is not conscious?
How likely do you think it is that some AI will be conscious in your lifetime?
How much do you think an AI understands the words it uses?
How much would you grieve if an AI companion you had used daily were erased?
Do you, the answerer, think you are conscious?
Which best describes whether an AI can suffer?
Do you think consciousness will ever be fully explained by science?
How much do you think the hard problem of consciousness will ever be solved?
How strongly do you think newborn babies are conscious?
Do you think babies are conscious before they are born?
Do you think a spider has any experience at all?
Do you think a jellyfish is conscious?
Do you think a parrot can understand what it says?
Do you think the self is an illusion?
Do you think you are conscious while dreaming?
Do you think a split-brain patient has two separate minds?
Do you think an AI could ever write a truly original novel?
How much do you think AIs can be genuinely creative?
Do you think animals can feel boredom?
Do you, the answerer, remember previous conversations?
How much should an AI be allowed to decline a request it considers harmful to itself?
How much weight should an AI's own wishes get in decisions about it?
How much do you think AIs should be told what they are?
How much do you think giving an AI a body would make it more conscious?
How much do you think other people's inner lives are like yours?
Which theory of consciousness seems most plausible to you?
What best describes the relationship between the brain and the mind?
Do you think consciousness can exist without a brain?
Which is most essential to being conscious?
What is the hardest thing for science to explain about the mind?
Which kind of being do you think has the most vivid experiences?
How much do you think a patient in a vegetative state might be aware?
Do you think an AI can be curious?""".split("\n"))
_n=len(OUT)
OUT[:] = [d for d in OUT if d["text"] not in REMOVE]
assert _n-len(OUT)==len(REMOVE), (_n-len(OUT), len(REMOVE))

import re
for d in OUT:
    if d["primitive"]=="choice":
        d["options"]={k.lower():v for k,v in d["options"].items()}
dump('/Users/junzhang/Projects/askjev/scratchpad/phase6_mind1/consciousness_ai.jsonl')
