import sys; sys.path.insert(0,'/Users/junzhang/Projects/askjev/scratchpad/phase6_mind1'); from lib import *; node("epistemics")
# ---------- CHOICE ----------
C("What does it take for a belief of yours to count as knowledge?", ["true_and_well_supported", "felt_certainty", "true_whatever_the_reason", ("reliable_method", "formed by a process that usually gets things right"), "agreed_by_experts", "not_sure"], "values")
C("If you guess the time from a stopped clock and happen to be right, what do you have?", [("knowledge", "you know the time"), ("lucky_true_belief", "a correct belief that isn't knowledge"), ("mere_guess", "not even a real belief"), "not_sure"], "evaluative")
C("Which kind of knowing do you value more in yourself?", [("knowing_how", "being able to do things, like ride a bike or cook"), ("knowing_that", "knowing facts and explanations"), "both_equally"], "values")
C("Which of your senses do you trust most to tell you what is really there?", ["sight", "hearing", "touch", "smell", "taste", "none_fully"], "personality")
C("What is your best reason for expecting the sun to rise tomorrow?", [("it_always_has", "past experience"), ("laws_of_physics", "we understand why it happens"), ("experts_say_so", None), ("no_real_reason", "I just assume it"), "other"], "evaluative")
C("When your memory of an event clashes with a photo of it, what do you usually conclude?", [("photo_is_right", None), ("memory_is_right", None), ("check_with_others", "ask people who were there"), ("unsure_which", None)], "personality")
C("Which is the weakest link in how people come to know things?", ["senses", "memory", "reasoning", "testimony_from_others", "emotions", "language"], "evaluative")
C("What most often makes you change your mind about something?", ["new_evidence", "a_good_argument", "personal_experience", "someone_i_respect", "time_and_reflection", "rarely_change_it"], "personality")
C("When you change your mind, how do you usually tell people?", [("say_so_openly", "I say I was wrong"), ("quietly_shift", "I just start saying the new view"), ("avoid_the_topic", None), ("only_tell_close_friends", None), "rarely_change_it"], "social")
C("What is the main thing that keeps people from changing their minds?", ["pride", "identity", "fear_of_looking_foolish", "lack_of_good_evidence", "laziness", "loyalty_to_a_group", "other"], "evaluative")
C("What should you look at first when judging whether an expert is worth listening to?", [("credentials", "degrees and titles"), ("track_record", "how often they were right before"), ("reputation_among_peers", None), ("clarity_of_explanation", None), ("independence", "no stake in the answer"), "other"], "values")
C("An expert with top credentials and a poor track record disagrees with an amateur who has been right many times. Whom do you side with?", ["the_expert", "the_amateur", "neither_until_more_evidence", "not_sure"], "evaluative")
C("Which kind of expert do you trust least?", ["financial_advisers", "nutrition_experts", "economists", "weather_forecasters", "doctors", "engineers", "none_in_particular"], "evaluative")
C("Which kind of expert do you trust most?", ["doctors", "engineers", "physicists", "pilots", "historians", "judges", "none_in_particular"], "evaluative")
C("When an expert says 'we don't know yet', how do you react?", [("trust_them_more", None), ("trust_them_less", None), ("look_for_someone_who_knows", None), ("no_change", None)], "personality")
C("What does a strong scientific consensus mean to you?", [("almost_certainly_true", None), ("best_current_guess", None), ("worth_questioning", None), ("often_driven_by_groupthink", None), "not_sure"], "values")
C("How would you describe someone who disagrees with the experts on almost everything?", [("independent_thinker", None), ("contrarian_for_its_own_sake", None), ("misinformed", None), ("occasionally_right_genius", None), "depends_on_the_person"], "evaluative")
C("Which is more dangerous for a thinker?", [("trusting_authority_too_much", None), ("distrusting_authority_too_much", None), "equally_dangerous"], "values")
C("When a hunch of yours turns out right, what do you usually credit?", [("real_intuition", "a skill built from experience"), ("chance", None), ("hidden_reasoning", "I had reasons I couldn't put into words"), "not_sure"], "personality")
C("In which area do you trust your intuition most?", ["judging_people", "physical_danger", "money_decisions", "creative_work", "technical_problems", "none"], "personality")
C("A friend's cousin got sick after a treatment that large studies say is safe. What weight should that story get?", [("a_lot", "it's a real case"), ("some", "worth noting"), ("very_little", "one case says little"), ("none", None)], "evaluative")
C("Which is more convincing to you?", [("one_vivid_story", None), ("a_dry_statistic", None), "equally_convincing"], "personality")
C("Why are personal stories so persuasive even when they mislead?", ["they_are_vivid", "they_come_from_people_we_know", "they_trigger_emotion", "numbers_are_hard_to_feel", "they_are_easy_to_remember", "other"], "evaluative")
C("When someone tells you a fact, what makes you most likely to believe it?", ["they_seem_confident", "they_cite_a_source", "they_are_an_expert", "it_fits_what_i_know", "they_have_no_reason_to_lie", "they_are_a_friend"], "personality")
C("What do you usually do after reading a surprising headline?", [("read_the_article", None), ("check_another_source", None), ("share_it", None), ("believe_it_and_move_on", None), ("ignore_it", None), ("doubt_it_and_move_on", None)], "personality")
C("Which part of a news story do you trust least?", ["the_headline", "the_quotes", "the_photos", "the_statistics", "the_expert_commentary", "none_in_particular"], "evaluative")
C("When you hear a rumor about someone you know, what do you usually do?", [("believe_it", None), ("assume_it_is_false", None), ("ask_the_person", None), ("wait_and_see", None), ("pass_it_on", None)], "social")
C("What is the main reason false information spreads faster than corrections?", ["it_is_more_exciting", "people_share_without_reading", "corrections_are_boring", "people_want_it_to_be_true", "algorithms_reward_it", "other"], "evaluative")
C("If you found out you had shared something false online, what would you do?", [("post_a_correction", None), ("delete_it_quietly", None), ("leave_it", None), ("message_those_who_saw_it", None)], "social")
C("Which is the clearest warning sign that a claim is a conspiracy theory?", [("unfalsifiable", "no evidence could ever count against it"), ("huge_secret_kept_by_many", None), ("evidence_against_seen_as_proof", None), ("relies_on_anonymous_insiders", None), ("explains_everything", None), "other"], "evaluative")
C("How do you usually respond when a friend shares a conspiracy theory?", [("argue_against_it", None), ("ask_questions", None), ("change_the_subject", None), ("hear_them_out", None), ("agree", None)], "social")
C("Which kind of person is most likely to spot a false conspiracy theory?", ["scientists", "journalists", "people_who_worked_in_big_organizations", "lawyers", "skeptical_ordinary_people", "anyone_can_fall_for_one"], "evaluative")
C("Which of these biases do you think affects you most?", [("confirmation_bias", "favoring evidence for what you already think"), ("overconfidence", None), ("hindsight_bias", "thinking you knew it all along"), ("anchoring", "sticking to the first number or idea you heard"), ("bandwagon_effect", "going along with what others think"), "none_of_these"], "personality")
C("When you search online for information on a question, what do you tend to type?", [("neutral_question", None), ("the_answer_i_expect", None), ("both_sides", None), ("whatever_comes_to_mind", None)], "personality")
C("When evidence for a belief you like is weak, what do you usually do?", [("hold_it_anyway", None), ("hold_it_more_loosely", None), ("look_for_better_evidence", None), ("drop_it", None)], "personality")
C("Which situation makes you most overconfident?", ["topics_i_studied_once", "things_i_read_recently", "predictions_about_people", "my_own_memory", "tasks_i_have_done_before", "none"], "personality")
C("How would you rather be seen?", [("confident", None), ("humble", None), ("accurate", "right as often as possible, whatever it looks like")], "values")
C("When everyone else in a room nods along to something you don't understand, what do you do?", [("ask_a_question", None), ("nod_along", None), ("look_it_up_later", None), ("ask_someone_privately", None)], "social")
C("Which kind of question is most likely to be forever unanswerable?", ["what_happens_after_death", "why_anything_exists", "what_other_minds_feel", "what_the_far_future_holds", "the_true_nature_of_time", "none_are_unanswerable"], "evaluative")
C("What is your attitude toward mysteries science may never solve?", [("accept_them", None), ("keep_trying_anyway", None), ("find_them_beautiful", None), ("find_them_frustrating", None), ("doubt_they_exist", None)], "values")
C("When solving a hard problem, which approach do you prefer?", [("first_principles", "reason it out from basics"), ("copy_what_works", "follow what others have done"), ("trial_and_error", None), ("ask_an_expert", None)], "personality")
C("Given two explanations that fit the facts equally well, which do you favor?", [("the_simpler", None), ("the_more_detailed", None), ("the_more_interesting", None), ("the_one_experts_prefer", None), ("neither_until_tested", None)], "values")
C("Someone claims to have seen a large unknown animal in a lake. What would you need before believing it?", [("their_word_is_enough", None), ("several_witnesses", None), ("clear_photos_or_video", None), ("physical_remains", None), ("nothing_would_convince_me", None)], "evaluative")
C("What makes a claim scientific in your eyes?", [("could_be_proven_wrong", None), ("made_by_scientists", None), ("uses_data", None), ("published_in_a_journal", None), ("widely_accepted", None), "not_sure"], "values")
C("When a weather forecast says rain is 'likely', what do you do?", [("take_an_umbrella", None), ("check_again_later", None), ("ignore_it", None), ("change_my_plans", None)], "personality")
C("Which word would you use for something you believe but would not bet on?", ["probably", "maybe", "likely", "possibly", "i_think", "i_wouldnt_say_it"], "personality")
C("When a friend you consider just as smart as you disagrees with you, what should you do?", [("hold_my_view", None), ("move_toward_their_view", None), ("suspend_judgment", None), ("dig_into_why_we_differ", None), ("agree_to_disagree", None)], "values")
C("When your whole friend group believes something you doubt, what do you usually do?", [("speak_up", None), ("keep_quiet", None), ("go_along_with_them", None), ("start_doubting_myself", None), ("look_into_it_more", None)], "social")
C("What is the main sign that you are believing something because you want it to be true?", [("i_avoid_checking_it", None), ("i_get_angry_when_questioned", None), ("it_makes_me_feel_good", None), ("i_cant_name_evidence", None), ("i_hold_others_to_higher_standards", None), "other"], "evaluative")
C("Which do you think people deceive themselves about most?", ["their_own_talents", "their_health", "their_relationships", "their_money", "their_motives", "how_others_see_them"], "evaluative")
C("How reliable is eyewitness testimony in your view?", [("very_reliable", None), ("mostly_reliable", None), ("often_mistaken", None), ("mostly_unreliable", None), "not_sure"], "evaluative")
C("What most often distorts what an eyewitness remembers?", ["stress", "leading_questions", "time_passing", "expectations", "talking_to_other_witnesses", "media_reports"], "evaluative")
C("How do you usually make predictions about things you care about?", [("gut_feeling", None), ("look_at_past_patterns", None), ("ask_informed_people", None), ("hope_for_the_best", None), ("avoid_predicting", None)], "personality")
C("When a prediction of yours turns out wrong, what do you usually do?", [("figure_out_why", None), ("blame_bad_luck", None), ("forget_about_it", None), ("insist_it_was_nearly_right", None), ("make_fewer_predictions", None)], "personality")
C("Which forecaster would you trust most?", [("confident_pundit", "always gives a clear answer"), ("cautious_hedger", "gives ranges and qualifiers"), ("track_record_keeper", "publishes past hits and misses"), ("insider", "has inside connections")], "evaluative")
C("How do you learn a new subject best?", ["reading", "hands_on_practice", "listening_to_explanations", "watching_videos", "discussing_it", "teaching_it"], "personality")
C("What is the best test that you really understand something?", [("explain_it_simply", None), ("use_it_to_solve_problems", None), ("answer_tricky_questions", None), ("teach_it", None), ("predict_what_happens", None)], "values")
C("What most sparks your curiosity?", ["how_things_work", "why_people_act_as_they_do", "the_distant_past", "the_natural_world", "mysteries_and_puzzles", "big_abstract_questions"], "personality")
C("When a question pops into your head, what do you usually do?", [("look_it_up_right_away", None), ("think_it_through_myself", None), ("ask_someone", None), ("let_it_go", None), ("note_it_for_later", None)], "personality")
C("Before accepting a claim, which question is most worth asking?", [("how_would_i_know", None), ("what_would_prove_it_wrong", None), ("who_benefits", None), ("how_common_is_this_generally", None), ("whats_the_source", None)], "values")
C("When you disagree with a book's argument, what do you usually do?", [("keep_reading", None), ("stop_reading", None), ("look_up_critics", None), ("write_down_objections", None), ("assume_i_missed_something", None)], "personality")
C("Which is the easiest way to sound convincing without being right?", ["speak_confidently", "use_jargon", "cite_a_study", "tell_a_personal_story", "repeat_it_often", "flatter_the_listener"], "evaluative")
C("Which is the best reason to hold a belief?", ["evidence", "logic", "experience", "tradition", "comfort", "trusted_testimony"], "values")
C("If you could only trust one source of information for the rest of your life, what would it be?", ["encyclopedias", "scientific_journals", "a_wise_friend", "my_own_experience", "news_outlets", "a_search_engine"], "values")
C("When two reliable sources contradict each other, what do you do?", [("pick_the_more_reputable", None), ("look_for_a_third", None), ("suspend_judgment", None), ("go_with_my_gut", None), ("split_the_difference", None)], "personality")
C("Which is the best way to tell whether a website is trustworthy?", ["who_runs_it", "whether_it_cites_sources", "how_professional_it_looks", "whether_others_link_to_it", "its_tone", "whether_it_sells_something"], "evaluative")
C("How do you feel about changing your mind in public?", [("proud", None), ("fine", None), ("a_little_embarrassed", None), ("very_embarrassed", None), ("i_avoid_it", None)], "personality")
C("Which is the more respectable thing to say in an argument?", [("you_convinced_me", None), ("let_me_think_about_it", None), ("we_see_it_differently", None), ("i_still_think_im_right", None)], "social")
C("After an argument ends, what do you most often do alone?", [("replay_my_points", None), ("reconsider_their_points", None), ("look_up_the_facts", None), ("forget_about_it", None)], "personality")
C("What is the best way to change a stubborn person's mind?", [("ask_questions", None), ("show_evidence", None), ("tell_a_story", None), ("give_them_time", None), ("let_them_find_out_themselves", None), ("you_cant", None)], "social")
C("Which of these beliefs of yours would be hardest for any evidence to shake?", ["that_i_exist", "that_the_outside_world_is_real", "that_my_loved_ones_are_who_they_seem", "that_basic_logic_works", "that_the_past_happened", "none"], "personality")
C("Which best describes how certain you usually feel about your beliefs?", [("very_sure_of_most", None), ("sure_of_some", None), ("tentative_about_most", None), ("unsure_of_nearly_everything", None)], "personality")
C("Is it possible that everything you remember is wrong?", [("yes_and_it_worries_me", None), ("yes_but_it_doesnt_matter", None), ("no_some_memories_are_certain", None), ("not_sure", None)], "evaluative")
C("How do you know that other people have thoughts like yours?", [("they_behave_like_me", None), ("they_tell_me", None), ("it_is_obvious", None), ("i_dont_really_know", None), ("science_shows_it", None)], "evaluative")
C("Which kind of claim do you check most carefully?", ["health_claims", "money_claims", "claims_about_people_i_know", "science_news", "historical_facts", "none_in_particular"], "personality")
C("When a study finds something surprising, what is your first thought?", [("fascinating", None), ("probably_wrong", None), ("who_paid_for_it", None), ("wait_for_more_studies", None), ("i_knew_it", None)], "personality")
C("Which is the most common mistake people make with evidence?", [("mixing_up_correlation_and_cause", None), ("ignoring_how_common_something_is", None), ("trusting_small_samples", None), ("cherry_picking", None), ("trusting_the_loudest_voice", None)], "evaluative")
C("If a coin lands heads many times in a row, what do you expect next?", [("heads_again", "it's on a streak"), ("tails", "it's due"), ("either_equally", None), ("suspect_the_coin", "it may be rigged")], "evaluative")
C("What does 'I'm fairly sure' mean when you say it?", [("almost_certain", None), ("more_likely_than_not", None), ("a_confident_guess", None), ("just_a_figure_of_speech", None)], "personality")
C("How do you treat advice from a friend who is not an expert but knows you well?", [("over_expert_advice", None), ("equal_to_expert_advice", None), ("below_expert_advice", None), ("depends_on_the_topic", None)], "social")
C("When you need information about a product, whose opinion do you trust most?", ["friends", "online_reviews", "expert_reviewers", "the_seller", "my_own_research", "nobody"], "social")
C("What would most weaken your trust in a source you usually rely on?", [("one_big_error", None), ("refusing_to_correct_errors", None), ("hidden_sponsorship", None), ("sensational_headlines", None), ("taking_sides", None)], "values")
C("Which is the better way to hold beliefs about the future?", [("as_firm_predictions", None), ("as_rough_odds", None), ("as_hopes", None), ("not_at_all", None)], "values")
C("If you had to explain how you know the Earth is round, what would you mostly rely on?", ["what_i_was_taught", "photos_from_space", "my_own_observations", "scientific_reasoning", "everyone_agrees", "i_couldnt_really_say"], "evaluative")
C("Which of your beliefs have you checked for yourself the least?", ["science_facts", "history", "health_advice", "facts_about_other_countries", "things_family_told_me", "none"], "personality")
C("When someone makes an extraordinary claim, where should the burden of proof lie?", [("on_the_claimant", None), ("on_the_doubter", None), ("shared", None), ("nobody_needs_to_prove_anything", None)], "values")
C("Which is the more honest answer to a hard question you haven't studied?", [("i_dont_know", None), ("my_best_guess_is", None), ("it_depends", None), ("ask_an_expert", None)], "values")
C("What is the main value of doubt?", [("protects_from_error", None), ("drives_discovery", None), ("keeps_you_humble", None), ("little_value", "it mostly paralyzes"), "other"], "values")
C("What is the main danger of too much doubt?", [("never_deciding", None), ("believing_nothing", None), ("seeming_cynical", None), ("falling_for_contrarians", None), ("no_danger", None)], "values")
C("What role should feelings play in deciding what is true?", [("none", None), ("a_warning_signal", None), ("an_equal_partner", None), ("the_main_guide", None)], "values")
C("When a math or logic answer feels wrong but you can't find a mistake, what do you trust?", [("the_calculation", None), ("the_feeling", None), ("recheck_until_they_agree", None), ("ask_someone", None)], "personality")
C("Which is harder for you to admit?", [("that_i_was_wrong", None), ("that_i_dont_know", None), ("that_i_was_fooled", None), ("that_i_changed_my_mind", None)], "personality")
C("Where do most of your beliefs about the world come from?", ["school", "family", "news_and_media", "friends", "my_own_experience", "books"], "personality")
C("When you notice that you believe the same things as everyone around you, what do you think?", [("we_must_be_right", None), ("i_should_check_it", None), ("its_a_coincidence", None), ("i_dont_notice", None)], "personality")
C("Which is the better sign that someone is knowledgeable?", [("they_answer_quickly", None), ("they_admit_limits", None), ("they_use_technical_terms", None), ("they_explain_simply", None), ("they_have_credentials", None)], "evaluative")
C("What should you do with a belief you only half remember reasons for?", [("keep_it", None), ("look_up_the_reasons_again", None), ("hold_it_loosely", None), ("drop_it", None)], "values")
C("When you learn that a fact from your school textbooks has been revised, how do you feel?", [("curious", None), ("annoyed", None), ("distrustful_of_other_facts", None), ("indifferent", None), ("glad_knowledge_improves", None)], "personality")
C("What is the main reason experts get things wrong?", ["overconfidence", "groupthink", "incentives", "incomplete_data", "the_world_is_complex", "narrow_focus"], "evaluative")
C("How should you treat an expert who has changed their view several times?", [("trust_them_more", None), ("trust_them_less", None), ("no_difference", None), ("depends_why_they_changed", None)], "values")
C("If your doctor and a well-reviewed online article disagree, which do you follow?", ["the_doctor", "the_article", "get_a_second_doctor", "my_own_judgment"], "personality")
C("What makes you suspicious of a statistic?", [("no_source", None), ("too_neat", None), ("confirms_what_the_speaker_wants", None), ("very_dramatic", None), ("i_rarely_am", None)], "personality")
C("What is the best response when you find a hole in your own argument?", [("admit_it", None), ("patch_it", None), ("rethink_the_conclusion", None), ("hope_nobody_notices", None)], "values")
C("Which record of a past event do you trust most?", ["written_diary_from_the_time", "photograph", "video", "official_report", "later_memoir", "oral_story"], "evaluative")
C("When you read something you strongly agree with, what do you usually do?", [("accept_it", None), ("check_it_just_as_hard", None), ("share_it", None), ("look_for_counterpoints", None)], "personality")
C("How would you describe your default attitude to new claims?", [("believe_until_disproven", None), ("doubt_until_proven", None), ("neutral_until_checked", None), ("depends_on_the_source", None)], "personality")
C("Which description of a skeptic fits your view?", [("wise", None), ("annoying", None), ("necessary", None), ("closed_minded", None), ("depends_on_the_skeptic", None)], "evaluative")
C("Which is the best reason to believe a scientific theory you can't check yourself?", [("it_makes_accurate_predictions", None), ("many_experts_accept_it", None), ("it_works_in_technology", None), ("it_has_survived_criticism", None), ("i_have_no_good_reason", None)], "values")
C("When an idea is unpopular, what does that tell you about it?", [("probably_wrong", None), ("nothing", None), ("worth_a_closer_look", None), ("probably_right", None)], "evaluative")
C("What do you most need before you'll say 'I know' rather than 'I think'?", [("personal_proof", None), ("strong_evidence", None), ("expert_confirmation", None), ("no_doubt_at_all", None), ("i_say_i_know_freely", None)], "personality")
C("Which type of thinker would you most like to be?", [("the_scientist", "tests ideas"), ("the_detective", "follows clues"), ("the_philosopher", "questions assumptions"), ("the_skeptic", "doubts claims"), ("the_explorer", "seeks new ideas"), ("the_judge", "weighs both sides")], "values")
C("Which is harder to fake?", [("credentials", None), ("a_track_record", None), ("confidence", None), ("a_citation", None), ("a_photo", None)], "evaluative")
C("Which is the most honest way to express that you might be wrong?", [("i_could_be_wrong", None), ("as_far_as_i_know", None), ("my_best_understanding_is", None), ("dont_quote_me", None), ("i_rarely_say_it", None)], "personality")
C("Which of these would you most want to be able to detect instantly?", ["lies", "bad_statistics", "logical_fallacies", "fake_photos", "hidden_motives", "my_own_bias"], "values")
C("When a rumor turns out to be true, what does that tell you about the person who spread it?", [("they_were_well_informed", None), ("they_got_lucky", None), ("they_were_still_wrong_to_spread_it", None), ("nothing", None)], "evaluative")
C("When you're unsure whether something is true, what do you usually say to others?", [("share_it_with_a_caveat", None), ("share_it_as_fact", None), ("say_nothing", None), ("check_first_then_share", None)], "social")
C("What is the main reason people stay in echo chambers?", ["comfort", "algorithms", "friend_groups", "distrust_of_outsiders", "lack_of_time", "not_knowing_they_are_in_one"], "evaluative")
C("How should you treat a belief that everyone in history has shared?", [("probably_true", None), ("still_needs_evidence", None), ("suspiciously_convenient", None), ("worth_respecting", None)], "values")
C("What makes you trust a scientific study?", [("large_sample", None), ("replicated_by_others", None), ("famous_journal", None), ("clear_methods", None), ("results_fit_what_i_know", None), ("no_conflicts_of_interest", None)], "evaluative")
C("Which is the better guide to the future?", [("the_past", None), ("expert_models", None), ("intuition", None), ("nothing_reliable", None)], "evaluative")
C("How do you usually decide between two conflicting news reports?", [("trust_the_familiar_outlet", None), ("compare_details", None), ("wait_for_updates", None), ("believe_the_one_i_prefer", None), ("dismiss_both", None)], "personality")
C("If you learned a cherished childhood story about your family was untrue, what would you do?", [("accept_it", None), ("keep_telling_it", None), ("dig_into_what_really_happened", None), ("prefer_not_to_know", None)], "personality")
C("Which is worse in a teacher?", [("admitting_ignorance_often", None), ("never_admitting_ignorance", None), "equally_bad"], "values")
C("Which is the better approach to a puzzle nobody has solved?", [("try_new_angles", None), ("study_why_others_failed", None), ("assume_it_is_unsolvable", None), ("wait_for_better_tools", None)], "values")
C("Which is the more embarrassing mistake?", [("being_gullible", None), ("being_too_cynical", None), "equally_embarrassing"], "personality")
C("What happens to your confidence when you learn more about a subject?", [("it_goes_up", None), ("it_goes_down", None), ("it_goes_down_then_up", None), ("it_stays_the_same", None)], "personality")

# ---------- SCORE ----------
S("How much do you rely on a single charismatic teacher or writer for your views on a subject?", ["I build my views from many sources", "One voice shapes my views a little", "One voice shapes my views quite a lot", "I mostly adopt one trusted voice's views wholesale"], "personality")
S("How do you handle a belief you hold that turns out to rest on a single source?", ["I keep believing it without a second thought", "I notice but keep believing it", "I start saying it with a caveat", "I look for other sources before repeating it", "I drop it until I find independent confirmation"], "personality")
S("How often do you notice that a belief of yours was based on luck rather than good reasons?", ["I have never noticed this happening", "I noticed it once or twice in my life", "I notice it now and then when I look back", "I catch it regularly and it changes how I hold beliefs"], "personality")
S("How much does the possibility that your senses deceive you affect how you live?", ["I never think about it", "I find it an interesting puzzle but it changes nothing", "It makes me double-check things like optical illusions", "It makes me hold most perceptions a little loosely", "It genuinely unsettles my sense of what is real"], "personality")
S("How do you react when someone asks you how you know something you just said?", ["I get irritated at being questioned", "I repeat the claim more firmly", "I say where I heard it", "I explain my reasoning step by step", "I welcome it and often realize I'm less sure than I sounded"], "personality")
S("How much do you trust a conclusion you reached by reasoning alone, with no data?", ["I don't trust it at all until I see evidence", "I treat it as a guess to be tested", "I trust it for small everyday matters", "I trust it about as much as observed facts", "I trust careful reasoning more than messy data"], "values")
S("How much does a person's confidence affect whether you believe them?", ["Confidence makes no difference to me", "It slightly tips me when I have nothing else to go on", "It noticeably raises my belief", "I usually believe confident people", "Very confident people almost always convince me"], "personality")
S("How much should a scientist's funding source affect whether you trust their results?", ["Not at all; the data speaks for itself", "It's worth a mention but rarely matters", "It makes me read the study more carefully", "It makes me wait for independent replication", "I discount any study funded by an interested party"], "values")
S("How do you respond when evidence against your view comes from someone you dislike?", ["I dismiss it because of who said it", "I take it less seriously than usual", "I try to judge it on its merits but struggle", "I judge it exactly as I would from anyone else"], "personality")
S("How often do you look for the strongest version of an argument you reject?", ["Never; I know it's wrong", "Only when I'm forced to", "Sometimes, when the topic matters to me", "Usually before I argue against it", "Always; I try to state it better than its supporters do"], "personality")
S("How do you handle a child who asks you a question you can't answer?", ["I make up an answer", "I give a vague answer and move on", "I say I don't know", "I say I don't know and we look it up together"], "social")
S("How do you treat a claim that can't be proven wrong by any possible evidence?", ["I find such claims especially convincing", "I treat it like any other claim", "I'm somewhat wary of it", "I treat it as not really saying anything about the world"], "values")
S("How much do you think you'd resist believing a comforting falsehood?", ["I'd happily believe it if it made me feel better", "I'd probably believe it without checking", "I'd want some evidence but would lean toward it", "I'd check it as carefully as an unwelcome claim", "I'd check it extra carefully because I want it to be true"], "personality")
S("How much do you think your memory of an important day has changed over the years?", ["Not at all; I remember it exactly", "Only minor details have slipped", "Some parts are probably reconstructed", "Much of it is probably a retold story now"], "evaluative")
S("How do you react when a friend remembers a shared event differently from you?", ["I insist my version is right", "I assume they're mistaken but let it go", "I figure we're both partly right", "I check photos or messages to settle it", "I assume my own memory is just as likely wrong"], "social")
S("How much should one eyewitness be enough to convict someone of a serious crime?", ["One clear eyewitness should be enough", "It should be enough if the witness seems very sure", "It should count but needs some support", "It should need strong physical evidence too", "One eyewitness should never be enough"], "values")
S("How often do you write down predictions so you can check them later?", ["Never", "I've done it once as a joke", "I occasionally note a prediction about something big", "I often keep track of my forecasts", "I keep a regular record and review how I did"], "personality")
S("How do you describe your chances when making a plan that could fail?", ["I assume it will definitely work", "I say it will probably work without thinking much", "I think through what could go wrong", "I estimate the odds in rough words like likely or unlikely", "I make a backup plan for the likely failure points"], "personality")
S("How much do you enjoy learning facts that overturn common knowledge?", ["I dislike it; it's unsettling", "I don't care either way", "I find it mildly interesting", "I love it and share it", "I actively hunt for these facts"], "personality")
S("How far do you go to understand how something you use every day works?", ["I never wonder how it works", "I wonder briefly but don't look it up", "I look up a quick explanation now and then", "I often read in depth about how things work", "I take things apart or build models to understand them"], "personality")
S("How do you judge an argument that reaches a conclusion you like?", ["I accept it immediately", "I accept it unless something is obviously wrong", "I check it about as hard as any argument", "I check it harder than usual because I'm biased"], "personality")
S("How much does hearing a claim repeated many times make you believe it?", ["Repetition makes no difference to me", "It makes the claim feel slightly familiar", "I notice I start believing things I hear often", "Repetition is often what convinces me"], "personality")
S("How do you treat a surprising fact you hear at a dinner party?", ["I repeat it the next day as true", "I remember it as probably true", "I store it as interesting but unverified", "I look it up before I ever repeat it"], "personality")
S("How much do you trust the reviews on a product page?", ["I believe them fully", "I trust the overall rating", "I read several and look for patterns", "I mainly trust the negative ones", "I assume many are fake and ignore them"], "evaluative")
S("How do you respond when two experts give opposite advice on something you must decide?", ["I pick whoever I heard first", "I pick whoever seems more confident", "I pick whoever has the better credentials", "I look at their reasons and track records", "I seek a third opinion and look at the evidence myself"], "personality")
S("How much weight should the majority of ordinary people's opinion carry on a technical question?", ["It should decide the matter", "It should carry heavy weight", "It should be one consideration among many", "It should carry little weight next to experts", "It should carry no weight at all"], "values")
S("How much do you trust a claim more because it is written in a textbook?", ["Not at all more", "Slightly more", "Considerably more", "I treat textbook claims as settled fact"], "evaluative")
S("How do you act when you realize you can't tell whether a photo online is real?", ["I assume it's real", "I share it with a note saying I'm unsure", "I don't share it", "I try a reverse image search or similar check", "I assume it's fake until proven otherwise"], "personality")
S("How often do you notice yourself defending a view mainly because you said it earlier?", ["Never", "Rarely, and only in heated arguments", "Sometimes, and I try to stop", "Often, it's a habit I know I have"], "personality")
S("How do you feel when you learn a belief you held for years was false?", ["Humiliated and defensive", "Embarrassed but I accept it", "Neutral; it happens", "Pleased that I now know better", "Excited; it's one of my favorite feelings"], "personality")
S("How strongly would you need to be shown you're wrong before admitting it about something you care deeply about?", ["A single good point would do", "A clear argument would do", "Solid evidence from a source I trust", "Overwhelming evidence from many sources", "I doubt anything would move me"], "personality")
S("How much should a successful prediction raise your trust in someone's judgment?", ["Not at all; it could be chance", "A little", "Noticeably, if the prediction was specific", "A lot; being right is what matters"], "values")
S("How much do you think intelligence protects a person from believing nonsense?", ["It makes no difference", "It helps a little", "It helps a lot", "Smart people are nearly immune", "Smart people are better at rationalizing nonsense"], "evaluative")
S("How do you react when a stranger online gives you information that corrects you?", ["I ignore it", "I argue back", "I check whether they're right", "I thank them if they're right", "I thank them publicly and update my post"], "social")
S("How often do you ask 'compared to what?' when you hear a statistic?", ["Never", "Rarely", "When the number seems dramatic", "Usually", "Almost every time"], "personality")
S("How much should an idea's age count toward believing it?", ["Old ideas are probably wrong", "Age makes no difference", "Surviving a long time counts slightly in its favor", "Long-held ideas deserve strong default trust"], "values")
S("How much do you agree that the simplest explanation is usually the right one?", ["Simple explanations are usually naive", "Simplicity tells us little about truth", "Simpler explanations are a good starting point", "Simpler explanations are usually right", "I nearly always go with the simplest explanation"], "values")
S("How much evidence would you need to believe someone had a genuine photographic memory?", ["Their word would be enough", "A quick demonstration would do", "Repeated tests under controlled conditions", "Scientific study by independent researchers", "I would never believe it"], "evaluative")
S("How much do you think the way a question is worded shapes your answer?", ["Not at all; my views are fixed", "Only on trivial questions", "Somewhat, on topics I haven't thought about", "A lot, on most topics"], "personality")
S("How do you react when a quiz reveals you know less about a topic than you thought?", ["I blame the quiz", "I shrug it off", "I feel a bit humbled", "I go learn more about the topic", "I adjust how confidently I talk about it from then on"], "personality")
S("How carefully do you separate what you saw from what you concluded when telling a story?", ["I tell it however it sounds best", "I mix them without noticing", "I try to keep them apart for important stories", "I always say what I saw versus what I guessed"], "personality")
S("How much do you trust knowledge that comes from long practice but can't be put into words?", ["Not at all; if it can't be explained it isn't knowledge", "A little, as a hint", "As much as knowledge from books", "More than book learning"], "values")
S("How much do you think people can know about what goes on in a stranger's mind?", ["Nothing at all", "Only what they tell us", "A fair amount from their behavior and face", "Almost everything, if we pay attention"], "evaluative")
S("How much do you trust that the future will resemble the past?", ["I don't; anything could happen", "Only for the laws of nature", "For most practical matters", "Almost completely"], "evaluative")
S("How willing are you to act on a belief you're only moderately sure of?", ["I never act until I'm certain", "Only when the stakes are tiny", "When waiting would cost more than being wrong", "Readily; most decisions have to be made that way"], "personality")
S("How much do you think your own opinions have been shaped by where you grew up?", ["Not at all; I reasoned them out myself", "A little", "A fair amount", "Most of them come from my upbringing"], "personality")
S("How do you react when an algorithm keeps showing you only content you agree with?", ["I never notice", "I notice but enjoy it", "I occasionally search for other views", "I deliberately change what I follow to break it up"], "personality")
S("How do you treat claims made by someone selling a product?", ["I take them at face value", "I trust them mostly", "I discount them somewhat", "I assume they're exaggerated", "I ignore them and look for independent reviews"], "evaluative")
S("How much do you feel you understand how a toilet or zipper works, if you had to explain it in detail?", ["I couldn't explain it at all", "I could give a vague idea", "I could explain the main parts", "I could explain it fully to a child"], "personality")
S("How much should you trust a friend's advice in an area where they have lots of experience but no training?", ["Not at all", "A little", "About as much as a trained professional", "More than a professional who lacks experience"], "values")
S("How much does admitting uncertainty make a speaker seem trustworthy to you?", ["It makes them seem weak and less trustworthy", "It makes no difference", "It makes them a bit more trustworthy", "It makes them far more trustworthy"], "evaluative")
S("How do you tell the difference between a mystery and something you just haven't looked into?", ["I don't; if I don't know it, it's a mystery", "I sometimes check whether anyone knows the answer", "I usually check before calling something unknown", "I always check what experts know before calling it a mystery"], "personality")
S("How much should extraordinary claims need more evidence than ordinary ones?", ["Every claim needs the same evidence", "Slightly more", "Clearly more", "Vastly more"], "values")
S("How ready are you to believe a scientific finding that seems absurd?", ["I reject it outright", "I doubt it until it's repeated", "I take it seriously if the source is strong", "I accept it; reality is often absurd"], "evaluative")
S("How much of what you know about the world have you verified yourself?", ["Almost none of it", "A small part", "A good part of the practical stuff", "Most of it"], "evaluative")
S("How do you handle a question at work that you can only half answer?", ["I give a confident full answer anyway", "I give my half answer as if it's complete", "I give what I know and flag the gap", "I say I'm unsure and point to someone who knows"], "social")
S("How much do you trust a claim if it comes with a precise-sounding statistic?", ["Much less; it seems like a trick", "Slightly less", "No differently", "Slightly more", "Much more; numbers make it feel solid"], "personality")
S("How quickly do you form an opinion on a new controversy?", ["Instantly, from the headline", "Within a few minutes of reading", "After hearing from a couple of sides", "Only after days of reading", "I usually stay undecided"], "personality")
S("How much should you revise your view when a trusted source is caught in one lie?", ["Not at all; everyone makes mistakes", "Slightly", "Substantially, for everything they said", "Completely; I would stop trusting them"], "values")
S("How deeply do you question the assumptions behind advice you're given?", ["I just follow advice", "I question it only when it seems odd", "I often ask why before following", "I rarely follow advice until I understand the reasoning"], "personality")
S("How much do you trust knowledge passed down through family sayings and folk wisdom?", ["Not at all", "Only as a starting point", "About as much as expert advice", "More than modern expert advice"], "evaluative")
S("How strongly do you believe that some questions have no answer at all?", ["Every question has an answer", "Almost every question has an answer", "Some questions may be meaningless", "Many deep questions have no answer"], "evaluative")
S("How do you feel about living with questions you can't answer?", ["It torments me", "It bothers me", "I can live with it", "I find it peaceful", "I enjoy it"], "personality")
S("How much should someone's feeling of certainty count as evidence they're right?", ["It should count for nothing", "It counts for a little", "It counts for a fair amount", "It is strong evidence"], "values")
S("When you catch a mistake in something you've published or sent, what do you do?", ["I leave it and hope no one notices", "I fix it quietly", "I fix it and mention it to anyone affected", "I fix it and add a visible correction note"], "values")
S("How much would an expert's refusal to debate critics lower your trust in them?", ["Not at all", "A little", "Noticeably", "A great deal"], "evaluative")
S("How often do you go back to check if something you believed turned out true?", ["Never", "Only for big things", "Sometimes", "Often", "As a regular habit"], "personality")
S("How do you treat a friend's strong recommendation to try an alternative remedy?", ["I try it right away", "I try it if it seems harmless", "I look up evidence first", "I politely decline unless there's good evidence"], "social")
S("How much can pure logic tell us about the real world?", ["Nothing; only observation can", "A little, mostly about consistency", "A good deal when combined with facts", "Almost everything, if reasoned carefully"], "values")
S("How much do you think people's belief in their own objectivity is justified?", ["Not at all; nobody is objective", "Rarely", "Somewhat, for careful people", "Mostly; people can be objective when they try"], "evaluative")
S("How much does the tone of an article affect whether you believe it?", ["Not at all", "A little", "A fair amount", "It's often what decides it for me"], "personality")
S("How much do you trust an answer that you found through a single web search?", ["I take it as fact", "I trust it for everyday questions", "I check another result if it matters", "I check several sources before trusting it"], "personality")
S("How often do you change your mind on an issue after a long conversation with someone?", ["Never", "Rarely", "Occasionally", "Often"], "personality")
S("How strongly do you think that doubting everything is a sensible way to start thinking?", ["It is a pointless exercise", "It is useful only in philosophy class", "It is useful now and then", "It is the right way to begin any inquiry"], "values")
S("How well do you think you would do at spotting a skilled con artist?", ["I would almost surely be fooled", "I'd probably be fooled", "It's a toss-up", "I'd probably catch them", "I'd almost surely catch them"], "personality")
S("How much should scientists' past mistakes lower trust in science today?", ["Not at all; science corrects itself", "A little", "Somewhat", "A great deal"], "values")
S("How much do you revise your plans after bad news you didn't expect?", ["I carry on as before", "I adjust small details", "I rethink the plan", "I start over from scratch"], "personality")
S("How much should you trust a translation of an important document?", ["Completely", "Mostly", "With some caution about nuance", "Only if checked by a second translator"], "evaluative")
S("How much do you think crowds of ordinary guessers can beat experts at predicting things?", ["Never", "Rarely", "On some kinds of questions", "Often"], "evaluative")
S("How much do you trust your first reading of someone's written message's tone?", ["I always read tone correctly", "I'm usually right", "I often reread to check", "I assume I may misread and ask when it matters"], "personality")
S("How much should you trust something you remember reading but can't recall where?", ["Fully", "Mostly", "As a vague hunch", "Not until I find the source"], "personality")
S("How much should experts in a field agree before you call something settled?", ["A few experts agreeing is enough", "Most experts should agree", "Nearly all experts should agree", "Nothing is ever settled"], "values")
S("How often do you notice you're more critical of evidence that goes against your team, school, or hometown?", ["Never", "Rarely", "Sometimes", "Often"], "personality")
S("How much can children be trusted as sources of what happened in an event they saw?", ["Not at all", "Only for simple facts", "About as much as adults", "More than adults; they have less reason to spin"], "evaluative")

# ---------- NOUL ----------
N("Can a person know something that turns out to be false?", "evaluative")
N("If you believe something true for a bad reason, do you know it?", "evaluative")
N("Is knowing how to ride a bike a real kind of knowledge?", "evaluative")
N("Is it reasonable to trust your senses even though they sometimes deceive you?", "values")
N("Is past experience a good enough reason to expect the future to be similar?", "evaluative")
N("Could you be dreaming right now without knowing it?", "evaluative")
N("Do you think you could be completely wrong about something you feel absolutely sure of?", "personality")
N("Have you ever changed your mind about something because of a single conversation?", "personality")
N("Do you find it hard to change your mind once you've said your view out loud?", "personality")
N("Would you rather hear an uncomfortable truth than a comforting mistake?", "values")
N("Should experts be trusted less when they have something to gain from what they say?", "values")
N("Is a strong track record more important than formal credentials when judging an expert?", "values")
N("Would you take a medicine your doctor recommends without reading anything about it?", "personality")
N("Can the majority of experts be wrong about something important at the same time?", "evaluative")
N("Do you enjoy holding a view that almost nobody around you shares?", "personality")
N("Do you think statistics can describe an individual person's situation?", "evaluative")
N("Is intuition just fast reasoning based on experience?", "evaluative")
N("Can a single dramatic story ever outweigh large studies?", "evaluative")
N("Do you usually believe what strangers tell you about facts?", "personality")
N("Should you believe a claim from a trustworthy person even if it sounds unlikely?", "values")
N("Do you usually read past the headline before sharing an article?", "personality")
N("Have you ever believed a rumor that turned out to be false?", "personality")
N("Do you think you could be fooled by a well-made fake video?", "personality")
N("Would you tell a friend if you thought they had fallen for a hoax?", "social")
N("Have you ever been drawn toward a conspiracy theory yourself?", "personality")
N("Do you think a conspiracy theory can ever turn out to be true?", "evaluative")
N("Do you tend to notice evidence that supports what you already believe more than evidence against it?", "personality")
N("Do you think you are less biased than most people?", "personality")
N("Do you think people who argue for a living are more likely to fool themselves?", "evaluative")
N("Do you think the more someone knows about a field, the more aware they are of its gaps?", "evaluative")
N("Is humility about what you know a sign of strength?", "values")
N("Would you respect a leader more if they often said 'I don't know'?", "values")
N("Do you think some questions will be answered by science that people now call unanswerable?", "evaluative")
N("Do you like working a problem out from scratch rather than looking up how others did it?", "personality")
N("Should a claim that can never be tested be treated as meaningless?", "values")
N("Would you need more than a friend's word to believe they met a famous celebrity by chance?", "evaluative")
N("When you say something is 'likely', do you mean you'd bet on it?", "personality")
N("If a friend who is as informed as you disagrees, should you become less confident?", "values")
N("Do you tend to adopt the views of your closest friends?", "social")
N("Have you ever believed something mainly because you wanted it to be true?", "personality")
N("Is it possible to lie to yourself and believe the lie?", "evaluative")
N("Do you trust your memory of conversations more than other people's?", "personality")
N("Can a person vividly remember something that never happened?", "evaluative")
N("Would you trust an eyewitness who is completely confident more than one who hesitates?", "evaluative")
N("Do you keep track of how often your predictions come true?", "personality")
N("Do you enjoy making predictions about how things will turn out?", "personality")
N("Do you learn better by doing than by reading?", "personality")
N("Do you often fall down research rabbit holes out of curiosity?", "personality")
N("Do you think using simple rules of thumb usually leads to good judgments?", "values")
N("Is it possible to be too open-minded?", "values")
N("Do you think animals know things that humans cannot find out?", "evaluative")
N("Can a belief be useful even if it's false?", "values")
N("Should you ever believe something just because it makes you happier?", "values")
N("Is it wrong to spread a claim you haven't checked?", "values")
N("Do you feel uneasy when you can't look something up right away?", "personality")
N("Would you change a long-held belief if a respected teacher of yours told you it was wrong?", "personality")
N("Do you think talking a problem through with others makes your conclusions more reliable?", "values")
N("Do you think a good argument can convince you of something false?", "personality")
N("Do you think knowledge from books is less real than knowledge from experience?", "values")
N("Do you check who wrote an article before deciding whether to believe it?", "personality")
N("Do you think doubting everything would make life impossible to live?", "evaluative")
N("Is it better to suspend judgment than to guess when you're unsure?", "values")
N("Do you think it's possible to be certain that other people have minds?", "evaluative")
N("Would you trust a claim more if it came from someone who once admitted a big mistake?", "evaluative")
N("Do you think you have ever been wrong about a basic fact for most of your life?", "personality")
N("Do you believe that careful thinking can get people closer to the truth over time?", "values")
N("Do you ask people to poke holes in your ideas before you act on them?", "personality")
N("Do you think the people you disagree with have usually thought about it as much as you?", "social")
N("Do you believe the simplest explanation for a strange event is usually a mundane one?", "evaluative")

dump('/Users/junzhang/Projects/askjev/scratchpad/phase6_mind1/epistemics.jsonl')
