"""Customer Support Tickets (Tobias Bueck, HF Tobi-Bueck/customer-support-tickets): helpdesk emails
(subject + body) labelled with the queue they were routed to and a priority. English rows only.
The tickets are synthetic (generated by the author's ticket generator), and the labels are the
generator's; spot checks show some noisy queue/priority labels, so treat truth as weak.

Templates (separate salted samples of the same deduplicated pool):
- "support_tickets.queue" (Choice, node support.routing): which of the 10 queues should handle the
  ticket. Truth = queue. Round-robin over queues (the rarest queues are used up first).
- "support_tickets.priority" (Score, node support.urgency_frustration): three situation levels for
  low / medium / high priority. Truth = level index. One third per level.
"""

from __future__ import annotations

import re
from collections import defaultdict
from pathlib import Path
from typing import Iterator

import httpx
import polars as pl

from askjev.model import Question
from askjev.sampling import env_int, hash_order

NAME = "support_tickets"
URL = "https://huggingface.co/api/datasets/Tobi-Bueck/customer-support-tickets/parquet/default/train/0.parquet"
TARGET_QUEUE = env_int("TARGET_SUPPORT_TICKETS_QUEUE", 2500)
TARGET_PRIORITY = env_int("TARGET_SUPPORT_TICKETS_PRIORITY", 2500)
LICENSE = "CC-BY-NC-4.0"

QUEUE_TEXT = "Which team should handle `ticket`?"
QUEUES = {  # key (Jev sees it) -> dataset queue, description from the dataset card
    "technical_support": ("Technical Support", "Technical issues and support requests"),
    "customer_service": ("Customer Service", "Customer inquiries and service requests"),
    "billing_and_payments": ("Billing and Payments", "Billing issues and payment processing"),
    "product_support": ("Product Support", "Support for product-related issues"),
    "it_support": ("IT Support", "Internal IT support and infrastructure issues"),
    "returns_and_exchanges": ("Returns and Exchanges", "Product returns and exchanges"),
    "sales_and_pre_sales": ("Sales and Pre-Sales", "Sales inquiries and pre-sales questions"),
    "human_resources": ("Human Resources", "Employee inquiries and HR-related issues"),
    "service_outages_and_maintenance": ("Service Outages and Maintenance", "Service interruptions and maintenance"),
    "general_inquiry": ("General Inquiry", "General inquiries and information requests"),
}
QUEUE_KEY = {raw: key for key, (raw, _) in QUEUES.items()}
QUEUE_OPTIONS = {key: desc for key, (_, desc) in QUEUES.items()}

PRIORITY_TEXT = "How urgent is `ticket`?"
PRIORITIES = ["low", "medium", "high"]
PRIORITY_LEVELS = [
    "A question, feature request or routine update that can be answered whenever the team gets to it",
    "A problem that slows the customer down or keeps recurring, such as poor performance or an "
    "intermittent error, but their work can go on while it is fixed",
    "A system outage, security breach, data loss or major malfunction that stops the customer's work "
    "and needs attention right away",
]
SENSITIVE = re.compile(r"\b(suicid\w*|self-harm|sexual\w*|porn\w*|nude\w*)\b", re.I)


def fetch(raw_dir: Path) -> None:
    out = raw_dir / "train.parquet"
    if out.exists():
        return
    r = httpx.get(URL, follow_redirects=True, timeout=300)
    r.raise_for_status()
    out.write_bytes(r.content)


def _clean(s: str | None) -> str:
    if not s:
        return ""
    s = s.replace("\\n", "\n")
    lines = [" ".join(l.split()) for l in s.split("\n")]
    return re.sub(r"\n{3,}", "\n\n", "\n".join(lines)).strip()


def normalize(raw_dir: Path) -> Iterator[Question]:
    df = pl.read_parquet(raw_dir / "train.parquet").with_row_index("row").filter(pl.col("language") == "en")
    seen: set[str] = set()
    pool = []
    for r in df.select("row", "subject", "body", "queue", "priority", "type").iter_rows(named=True):
        body = _clean(r["body"])
        if len(body) < 40 or r["queue"] not in QUEUE_KEY or r["priority"] not in PRIORITIES:
            continue
        key = " ".join(body.lower().split())
        if key in seen:
            continue
        seen.add(key)
        subject = _clean(r["subject"])
        ticket = (f"Subject: {subject}\n\n{body}" if subject else body)[:1500]
        pool.append({**r, "ticket": ticket})

    def emit(items, tid):
        for r in sorted(items, key=lambda x: x["row"]):
            flags = {"flags": ["sensitive"]} if SENSITIVE.search(r["ticket"]) else {}
            meta = {"queue_raw": r["queue"], "priority_raw": r["priority"], "type": r["type"],
                    "synthetic_tickets": True, **flags}
            if tid == "support_tickets.queue":
                yield Question(
                    text=QUEUE_TEXT, primitive="choice", hemisphere="machine", origin="dataset", source=NAME,
                    options=QUEUE_OPTIONS, state={"ticket": r["ticket"]}, shape="route",
                    node_hint="machine.support.routing", template_id=tid, source_item_id=f"train:{r['row']}",
                    license=LICENSE, truth=QUEUE_KEY[r["queue"]], meta=meta,
                )
            else:
                yield Question(
                    text=PRIORITY_TEXT, primitive="score", hemisphere="machine", origin="dataset", source=NAME,
                    options=PRIORITY_LEVELS, state={"ticket": r["ticket"]}, shape="score",
                    node_hint="machine.support.urgency_frustration", template_id=tid,
                    source_item_id=f"train:{r['row']}", license=LICENSE,
                    truth=PRIORITIES.index(r["priority"]), meta=meta,
                )

    # Queue: round-robin over queues in salted hash order.
    by_q = defaultdict(list)
    for r in pool:
        by_q[r["queue"]].append(r)
    orders = {q: hash_order(v, lambda x: x["row"], f"tickets.queue.{q}") for q, v in by_q.items()}
    picked, i = [], 0
    while len(picked) < TARGET_QUEUE and any(i < len(v) for v in orders.values()):
        for q in sorted(orders):
            if len(picked) < TARGET_QUEUE and i < len(orders[q]):
                picked.append(orders[q][i])
        i += 1
    yield from emit(picked, "support_tickets.queue")

    # Priority: equal thirds, salted hash order.
    picked = []
    for j, p in enumerate(PRIORITIES):
        k = TARGET_PRIORITY // 3 + (1 if j < TARGET_PRIORITY % 3 else 0)
        picked += hash_order([r for r in pool if r["priority"] == p], lambda x: x["row"], f"tickets.prio.{p}")[:k]
    yield from emit(picked, "support_tickets.priority")
