"""Generate docs/corpus.md: what's in the database, by source, with license and coverage (regenerate any time)."""
from askjev import db
from askjev.config import ROOT
from askjev.mix import mix_report

with db.connect() as conn:
    rows = conn.execute("""
        select q.source, q.hemisphere, count(*) n,
               count(*) filter (where q.truth is not null) truth,
               count(*) filter (where exists (select 1 from human_dists h where h.question_id=q.id)) human,
               count(*) filter (where not q.display_ok) hidden,
               count(m.top) answered, max(q.license) license
        from questions q left join question_meta m on m.question_id=q.id
        group by 1,2 order by 3 desc""").fetchall()
    tot = conn.execute("""select count(*) q, (select count(*) from probes) p, (select count(*) from answers) a,
                              (select count(*) from calls) c, (select count(*) from nodes where status='active') nodes,
                              (select count(*) from human_dists) h from questions""").fetchone()
L = ["# Corpus (generated by scripts/corpus_report.py)", "",
     f"**{tot['q']:,} canonical questions**, {tot['nodes']} active tree nodes, {tot['p']:,} probes, {tot['a']:,} answers, "
     f"{tot['c']:,} cached Jev calls, {tot['h']:,} human distributions.", "",
     "| source | hemisphere | questions | answered | truth | human data | hidden | license |", "|---|---|---|---|---|---|---|---|"]
for r in rows:
    L.append(f"| {r['source']} | {r['hemisphere']} | {r['n']:,} | {r['answered']:,} | {r['truth']:,} | {r['human']:,} | {r['hidden']:,} | {(r['license'] or '')[:70]} |")
L += ["", "## Mix vs targets", "", mix_report(markdown=True)]
(ROOT / "docs" / "corpus.md").write_text("\n".join(L) + "\n")
print("\n".join(L[:4]))
